#pragma once

#include "resource_variant_links.h"

#include <algorithm>
#include <array>
#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <functional>
#include <set>
#include <span>
#include <stdexcept>
#include <string>
#include <vector>

namespace xenos::resources::variants {
namespace detail {
struct Element {
    uint32_t format;
    uint16_t offset;
    uint8_t stream, usage, index;
};
struct Declaration {
    uint16_t first;
    uint8_t count, extent;
};
struct Source {
    uint64_t hash;
    uint32_t size;
    uint16_t first, count;
};

// BEGIN GENERATED METADATA
// Generated by tools/generate_shader_variants.py. Metadata only; no microcode.
// Original XEX image SHA256: cb756b46092e448923517bf660b44ad1a0651c2860882b43ae021f4ad4290f71
// SDK width table 0x82216538; component swizzle masks 0x82185A40.
inline constexpr uint8_t widths[] = {
    0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 1,
    2, 1, 2, 4, 1, 2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0,
};
inline constexpr uint16_t swizzleMasks[] = {
    0xe000, 0x1c00, 0x0380, 0x0070, 0x0008, 0x000a, 0x0008, 0x000e
};
inline constexpr Element elements[] = {
    {0x002a23b9, 0, 0, 0, 0},
    {0x002a23b9, 12, 0, 3, 0},
    {0x002a23b9, 24, 0, 6, 0},
    {0x002c23a5, 36, 0, 5, 0},
    {0x002c83a4, 44, 0, 1, 0},
    {0x001a23a6, 48, 0, 5, 3},
    {0x002c23a5, 64, 0, 5, 1},
    {0x001a23a6, 72, 0, 5, 2},
    {0x002a23b9, 0, 0, 0, 0},
    {0x002a23b9, 12, 0, 3, 0},
    {0x002a23b9, 24, 0, 6, 0},
    {0x002c23a5, 36, 0, 5, 0},
    {0x002c83a4, 44, 0, 1, 0},
    {0x001a23a6, 48, 0, 5, 1},
    {0x002a23b9, 0, 0, 0, 0},
    {0x001a23a6, 0, 0, 0, 0},
    {0x002c23a5, 16, 0, 5, 0},
    {0x001a23a6, 24, 0, 10, 0},
    {0x00182886, 40, 0, 10, 1},
    {0x001a23a6, 0, 0, 0, 0},
    {0x002c23a5, 16, 0, 5, 0},
    {0x002c23a5, 0, 0, 0, 0},
    {0x002c23a5, 0, 0, 0, 0},
    {0x002c23a5, 8, 0, 5, 0},
    {0x002a23b9, 0, 0, 0, 0},
    {0x002a23b9, 12, 0, 3, 0},
    {0x002a23b9, 24, 0, 6, 0},
    {0x002c23a5, 36, 0, 5, 0},
    {0x002c83a4, 44, 0, 1, 0},
    {0x001a23a6, 48, 0, 5, 1},
    {0x002a23b9, 0, 0, 0, 0},
    {0x001a2286, 16, 0, 6, 0},
    {0x001a2286, 20, 0, 7, 0},
    {0x001a2286, 24, 0, 3, 0},
    {0x002c23a5, 32, 0, 5, 0},
    {0x00182886, 28, 0, 10, 0},
};
inline constexpr Declaration declarations[] = {
    {0, 8, 22}, // Original constructor 0x823B8848
    {8, 6, 16}, // Original constructor 0x823B8B70
    {14, 1, 3}, // Original constructor 0x824980E8
    {15, 4, 11}, // Original constructor 0x82555510
    {19, 2, 6}, // Original constructor 0x825CDB08
    {21, 1, 2}, // Original constructor 0x82763DE0
    {22, 2, 4}, // Original constructor 0x827A0CC8
    {24, 6, 16}, // Original constructor 0x827A3928
    {30, 6, 10}, // Observed packed static mesh; original SDK semantic mapping
};
inline constexpr uint32_t fetchMetadata[] = {
    0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x00205009, 0x00100005, 0x00006006, 0x00007007,
    0x00203008, 0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x00005009, 0x0020a00a, 0x00100003,
    0x00305004, 0x00100006, 0x00001007, 0x00306008, 0x0010000a, 0x0000300b, 0x0000600c, 0x0000500d,
    0x0000100e, 0x0021500f, 0x00100004, 0x00006005, 0x00007006, 0x00003007, 0x00005008, 0x0020a009,
    0x00100007, 0x00001008, 0x00006009, 0x0020300a, 0x00100005, 0x00006006, 0x00007007, 0x00003008,
    0x00205009, 0x00100008, 0x00003009, 0x0000500a, 0x0000100b, 0x0021500c, 0x00100005, 0x00006006,
    0x00007007, 0x00003008, 0x00005009, 0x0020a00a, 0x00100007, 0x00001008, 0x00306009, 0x00100005,
    0x00006006, 0x00007007, 0x00003008, 0x0020a009, 0x00100003, 0x00005004, 0x00215005, 0x00000003,
    0x00100005, 0x00003006, 0x00005007, 0x00215008, 0x00100008, 0x00003009, 0x0000600a, 0x0000500b,
    0x0000100c, 0x0001500d, 0x0002500e, 0x0023500f, 0x00100005, 0x00006006, 0x00007007, 0x00003008,
    0x00005009, 0x0020a00a, 0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x00005009, 0x0020a00a,
    0x00100008, 0x00003009, 0x0000600a, 0x0000500b, 0x0000100c, 0x0001500d, 0x0002500e, 0x0023500f,
    0x00100006, 0x00006007, 0x00007008, 0x00003009, 0x0000500a, 0x0020a00b, 0x00100005, 0x00006006,
    0x00007007, 0x00003008, 0x00005009, 0x0020a00a, 0x00100005, 0x00006006, 0x00007007, 0x00003008,
    0x00005009, 0x0030a00a, 0x00100006, 0x00003007, 0x00005008, 0x00001009, 0x0021500a, 0x00100006,
    0x00001007, 0x00306008, 0x00100009, 0x0000300a, 0x0000600b, 0x0000500c, 0x0000100d, 0x0001500e,
    0x0002500f, 0x00235010, 0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x00005009, 0x0020a00a,
    0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x0020a009, 0x00100005, 0x00006006, 0x00007007,
    0x00003008, 0x0030a009, 0x00100006, 0x00001007, 0x00006008, 0x00203009, 0x00100006, 0x00003007,
    0x00006008, 0x00005009, 0x0000100a, 0x0021500b, 0x00100008, 0x00003009, 0x0000600a, 0x0000500b,
    0x0000100c, 0x0001500d, 0x0002500e, 0x0023500f, 0x00100007, 0x00001008, 0x00006009, 0x0020300a,
    0x00100003, 0x00005004, 0x00215005, 0x00100009, 0x0000300a, 0x0000600b, 0x0000500c, 0x0000100d,
    0x0001500e, 0x0002500f, 0x00235010, 0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x00005009,
    0x0020a00a, 0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x00005009, 0x0020a00a, 0x00100006,
    0x00001007, 0x00306008, 0x00100003, 0x00305004, 0x00100009, 0x0000300a, 0x0000600b, 0x0000500c,
    0x0000100d, 0x0001500e, 0x0002500f, 0x00235010, 0x00100003, 0x00305004, 0x00100007, 0x00001008,
    0x00206009, 0x00100003, 0x00305004, 0x00100006, 0x00001007, 0x00206008, 0x00100006, 0x00001007,
    0x00006008, 0x00203009, 0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x00005009, 0x0020a00a,
    0x00100004, 0x00001005, 0x00206006, 0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x00005009,
    0x0020a00a, 0x00100008, 0x00003009, 0x0000600a, 0x0000500b, 0x0000100c, 0x0001500d, 0x0002500e,
    0x0023500f, 0x00100004, 0x00006005, 0x00007006, 0x00203007, 0x00100007, 0x00003008, 0x00006009,
    0x0000500a, 0x0000100b, 0x0001500c, 0x0002500d, 0x0023500e, 0x00100005, 0x00006006, 0x00007007,
    0x00003008, 0x00005009, 0x0020a00a, 0x00100005, 0x00001006, 0x00206007, 0x00100005, 0x00006006,
    0x00007007, 0x00003008, 0x00005009, 0x0020a00a, 0x00100004, 0x00006005, 0x00007006, 0x00003007,
    0x00005008, 0x0020a009, 0x00100006, 0x00003007, 0x00006008, 0x00005009, 0x0000100a, 0x0021500b,
    0x00100006, 0x00001007, 0x00206008, 0x00100003, 0x00205004, 0x00100006, 0x00003007, 0x00006008,
    0x00005009, 0x0000100a, 0x0001500b, 0x0002500c, 0x0023500d, 0x00100005, 0x00203006, 0x00100005,
    0x00006006, 0x00007007, 0x00003008, 0x00205009, 0x00100003, 0x00005004, 0x0000a005, 0x0031a006,
    0x00100003, 0x00205004, 0x00100008, 0x00003009, 0x0000600a, 0x0000500b, 0x0000100c, 0x0021500d,
    0x00100006, 0x00003007, 0x00005008, 0x00001009, 0x0021500a, 0x00100008, 0x00001009, 0x0000600a,
    0x0020300b, 0x00100006, 0x00001007, 0x00006008, 0x00201009, 0x00100007, 0x00001008, 0x00006009,
    0x0000300a, 0x0020100b, 0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x00005009, 0x0030a00a,
    0x00100005, 0x00006006, 0x00007007, 0x00203008, 0x00100005, 0x00006006, 0x00007007, 0x00003008,
    0x00005009, 0x0020a00a, 0x00100004, 0x00006005, 0x00007006, 0x00003007, 0x00205008, 0x00100004,
    0x00006005, 0x00007006, 0x00003007, 0x00305008, 0x00100005, 0x00006006, 0x00007007, 0x00003008,
    0x00005009, 0x0020a00a, 0x00100007, 0x00001008, 0x00206009, 0x00100008, 0x00001009, 0x0000600a,
    0x0020300b, 0x00100006, 0x00003007, 0x00006008, 0x00005009, 0x0000100a, 0x0021500b, 0x00100005,
    0x00006006, 0x00007007, 0x00003008, 0x0030a009, 0x00100008, 0x00001009, 0x0000600a, 0x0020300b,
    0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x00005009, 0x0020a00a, 0x00100008, 0x00003009,
    0x0000600a, 0x0000500b, 0x0000100c, 0x0021500d, 0x00100003, 0x00005004, 0x00215005, 0x00000003,
    0x00100003, 0x00305004, 0x00100003, 0x00305004, 0x00100005, 0x00006006, 0x00007007, 0x00003008,
    0x00005009, 0x0020a00a, 0x00100007, 0x00001008, 0x00006009, 0x0020300a, 0x00100007, 0x00003008,
    0x00005009, 0x0000100a, 0x0021500b, 0x00100006, 0x00001007, 0x00206008, 0x00100005, 0x00006006,
    0x00007007, 0x00003008, 0x00205009, 0x00100006, 0x00001007, 0x00006008, 0x00203009, 0x00100008,
    0x00003009, 0x0000600a, 0x0000500b, 0x0000100c, 0x0001500d, 0x0002500e, 0x0023500f, 0x00100009,
    0x0000300a, 0x0000600b, 0x0000500c, 0x0000100d, 0x0021500e, 0x00100005, 0x00001006, 0x00206007,
    0x00100006, 0x00001007, 0x00006008, 0x00203009, 0x00100003, 0x00005004, 0x0030a005, 0x00100003,
    0x00305004, 0x00100006, 0x00001007, 0x00006008, 0x00201009, 0x00100008, 0x00003009, 0x0000600a,
    0x0000500b, 0x0000100c, 0x0001500d, 0x0002500e, 0x0023500f, 0x00100006, 0x00001007, 0x00206008,
    0x00100006, 0x00006007, 0x00007008, 0x00003009, 0x0020500a, 0x00100006, 0x00003007, 0x00005008,
    0x00001009, 0x0021500a, 0x00100007, 0x00003008, 0x00006009, 0x0000500a, 0x0000100b, 0x0021500c,
    0x00100004, 0x00205005, 0x00100005, 0x00003006, 0x00205007, 0x00100005, 0x00003006, 0x00005007,
    0x0020a008, 0x00100006, 0x00001007, 0x00006008, 0x00203009, 0x00100003, 0x00305004, 0x00100006,
    0x00005007, 0x0020a008, 0x00100007, 0x00003008, 0x00005009, 0x0000100a, 0x0021500b, 0x00100004,
    0x00006005, 0x00007006, 0x00003007, 0x00005008, 0x0020a009, 0x00000003, 0x00100006, 0x00006007,
    0x00007008, 0x00003009, 0x0000500a, 0x0020a00b, 0x00100007, 0x00001008, 0x00006009, 0x0020300a,
    0x00100007, 0x00001008, 0x00006009, 0x0020300a, 0x00100007, 0x00006008, 0x00007009, 0x0000300a,
    0x0020500b, 0x00100007, 0x00003008, 0x00005009, 0x0000100a, 0x0021500b, 0x00100004, 0x00006005,
    0x00007006, 0x00003007, 0x00005008, 0x0020a009, 0x00100005, 0x00003006, 0x0020a007, 0x00100003,
    0x00205004, 0x00100006, 0x00001007, 0x00206008, 0x00100007, 0x00001008, 0x00006009, 0x0020300a,
    0x00100003, 0x00205004, 0x00100006, 0x00001007, 0x00206008, 0x00100006, 0x00006007, 0x00007008,
    0x00203009, 0x00100003, 0x00305004, 0x00100004, 0x00006005, 0x00007006, 0x00303007, 0x00100006,
    0x00006007, 0x00007008, 0x00203009, 0x00100004, 0x00006005, 0x00007006, 0x00203007, 0x00100003,
    0x00005004, 0x0000a005, 0x0031a006, 0x00100005, 0x00001006, 0x00006007, 0x00203008, 0x00100006,
    0x00003007, 0x00006008, 0x00005009, 0x0000100a, 0x0021500b, 0x00100006, 0x00003007, 0x00005008,
    0x00015009, 0x0022500a, 0x00100006, 0x00001007, 0x00006008, 0x00203009, 0x00100005, 0x00006006,
    0x00007007, 0x00003008, 0x00005009, 0x0030a00a, 0x00100008, 0x00003009, 0x0000600a, 0x0000500b,
    0x0000100c, 0x0001500d, 0x0002500e, 0x0023500f, 0x00100005, 0x00006006, 0x00007007, 0x00203008,
    0x00100009, 0x0000100a, 0x0000600b, 0x0020300c, 0x00100005, 0x00006006, 0x00007007, 0x00003008,
    0x0030a009, 0x00100006, 0x00003007, 0x00005008, 0x00001009, 0x0021500a, 0x00100005, 0x00001006,
    0x00006007, 0x00203008, 0x00100003, 0x00305004, 0x00100004, 0x00006005, 0x00007006, 0x00003007,
    0x00005008, 0x0020a009, 0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x00005009, 0x0030a00a,
    0x00100007, 0x00003008, 0x00006009, 0x0000500a, 0x0000100b, 0x0021500c, 0x00000003, 0x00100003,
    0x00305004, 0x00100006, 0x00003007, 0x00005008, 0x00001009, 0x0021500a, 0x00100004, 0x00006005,
    0x00007006, 0x00003007, 0x0030a008, 0x00100006, 0x00001007, 0x00006008, 0x00203009, 0x00100005,
    0x00006006, 0x00007007, 0x00003008, 0x0020a009, 0x00100007, 0x00001008, 0x00006009, 0x0020300a,
    0x00100008, 0x00003009, 0x0000600a, 0x0000500b, 0x0000100c, 0x0021500d, 0x00100004, 0x00006005,
    0x00007006, 0x00003007, 0x0020a008, 0x00100007, 0x00003008, 0x00006009, 0x0000500a, 0x0000100b,
    0x0021500c, 0x00100005, 0x00001006, 0x00206007, 0x00100003, 0x00305004, 0x00000003, 0x00100006,
    0x00003007, 0x00006008, 0x00005009, 0x0000100a, 0x0001500b, 0x0002500c, 0x0023500d, 0x0010000a,
    0x0000300b, 0x0000600c, 0x0000500d, 0x0000100e, 0x0001500f, 0x00025010, 0x00235011, 0x00100004,
    0x00001005, 0x00206006, 0x00100008, 0x00003009, 0x0000500a, 0x0000100b, 0x0021500c, 0x00100003,
    0x00205004, 0x00100006, 0x00001007, 0x00306008, 0x00100005, 0x00006006, 0x00007007, 0x00003008,
    0x00005009, 0x0020a00a, 0x00100003, 0x00305004, 0x00100003, 0x0030a004, 0x00100007, 0x00003008,
    0x00006009, 0x0000500a, 0x0000100b, 0x0001500c, 0x0002500d, 0x0023500e, 0x00100006, 0x00001007,
    0x00006008, 0x00003009, 0x0020100a, 0x00100007, 0x00001008, 0x00006009, 0x0020300a, 0x00100005,
    0x00006006, 0x00007007, 0x00003008, 0x0020a009, 0x00100005, 0x00001006, 0x00306007, 0x00100007,
    0x00001008, 0x00006009, 0x0020300a, 0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x00005009,
    0x0020a00a, 0x00000003, 0x00100006, 0x00006007, 0x00007008, 0x00003009, 0x0020500a, 0x00100005,
    0x00006006, 0x00007007, 0x00003008, 0x00005009, 0x0020a00a, 0x00100004, 0x00006005, 0x00007006,
    0x00003007, 0x00005008, 0x0030a009, 0x00100004, 0x00006005, 0x00007006, 0x00003007, 0x00305008,
    0x00100005, 0x00001006, 0x00306007, 0x00100003, 0x0030a004, 0x00100003, 0x00005004, 0x0020a005,
    0x00100007, 0x00003008, 0x00006009, 0x0000500a, 0x0000100b, 0x0021500c, 0x00100005, 0x00006006,
    0x00007007, 0x00003008, 0x00005009, 0x0030a00a, 0x00100007, 0x00003008, 0x00005009, 0x0000100a,
    0x0021500b, 0x00100004, 0x00001005, 0x00206006, 0x00100004, 0x00006005, 0x00007006, 0x00003007,
    0x0030a008, 0x00100008, 0x00001009, 0x0000600a, 0x0020300b, 0x00100008, 0x00003009, 0x0000600a,
    0x0000500b, 0x0000100c, 0x0001500d, 0x0002500e, 0x0023500f, 0x00100006, 0x00003007, 0x00006008,
    0x00005009, 0x0000100a, 0x0021500b, 0x00100004, 0x00006005, 0x00007006, 0x00003007, 0x00005008,
    0x0020a009, 0x00100006, 0x00006007, 0x00007008, 0x00003009, 0x0020a00a, 0x00100007, 0x00001008,
    0x00006009, 0x0000300a, 0x0020100b, 0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x0020a009,
    0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x0020a009, 0x00100007, 0x00006008, 0x00007009,
    0x0000300a, 0x0000500b, 0x0020a00c, 0x00100008, 0x00003009, 0x0000600a, 0x0000500b, 0x0000100c,
    0x0021500d, 0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x00005009, 0x0020a00a, 0x00100005,
    0x00001006, 0x00206007, 0x00100006, 0x00006007, 0x00007008, 0x00003009, 0x0020a00a, 0x00100006,
    0x00001007, 0x00306008, 0x00100004, 0x00006005, 0x00007006, 0x00003007, 0x00005008, 0x0030a009,
    0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x00205009, 0x00100005, 0x00001006, 0x00306007,
    0x00100007, 0x00003008, 0x00006009, 0x0000500a, 0x0000100b, 0x0001500c, 0x0002500d, 0x0023500e,
    0x00100006, 0x00001007, 0x00206008, 0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x00205009,
    0x00100003, 0x00005004, 0x00215005, 0x00100006, 0x00001007, 0x00006008, 0x00203009, 0x00100005,
    0x00006006, 0x00007007, 0x00203008, 0x00100004, 0x00006005, 0x00007006, 0x00003007, 0x00005008,
    0x0020a009, 0x00100008, 0x00001009, 0x0000600a, 0x0020300b, 0x00100007, 0x00001008, 0x00006009,
    0x0000300a, 0x0020100b, 0x00100007, 0x00003008, 0x00006009, 0x0000500a, 0x0000100b, 0x0021500c,
    0x00100005, 0x00001006, 0x00206007, 0x00100003, 0x00305004, 0x00100007, 0x00001008, 0x00006009,
    0x0020300a, 0x00100008, 0x00003009, 0x0000500a, 0x0000100b, 0x0021500c, 0x00100007, 0x00001008,
    0x00306009, 0x00100004, 0x00006005, 0x00007006, 0x00003007, 0x00205008, 0x00100005, 0x00001006,
    0x00206007, 0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x0030a009, 0x0010000a, 0x0000300b,
    0x0000600c, 0x0000500d, 0x0000100e, 0x0001500f, 0x00025010, 0x00235011, 0x00100005, 0x00001006,
    0x00306007, 0x00100004, 0x00006005, 0x00007006, 0x00003007, 0x00005008, 0x0020a009, 0x00100003,
    0x00005004, 0x00315005, 0x00100005, 0x00001006, 0x00006007, 0x00201008, 0x00100008, 0x00003009,
    0x0000500a, 0x0000100b, 0x0021500c, 0x00100008, 0x00001009, 0x0000600a, 0x0020300b, 0x00100007,
    0x00001008, 0x00006009, 0x0020300a, 0x00100004, 0x00006005, 0x00007006, 0x00003007, 0x0020a008,
    0x00100004, 0x00006005, 0x00007006, 0x00203007, 0x00100004, 0x00006005, 0x00007006, 0x00003007,
    0x00205008, 0x00100006, 0x00001007, 0x00006008, 0x00201009, 0x00000003, 0x00100007, 0x00003008,
    0x00005009, 0x0000100a, 0x0021500b, 0x00100007, 0x00001008, 0x00006009, 0x0020300a, 0x00100003,
    0x00005004, 0x0030a005, 0x00100005, 0x00001006, 0x00006007, 0x00203008, 0x00100007, 0x00003008,
    0x00005009, 0x0000100a, 0x0021500b, 0x00100003, 0x00005004, 0x00315005, 0x00100006, 0x00001007,
    0x00306008, 0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x00005009, 0x0020a00a, 0x00100003,
    0x00305004, 0x00100005, 0x00006006, 0x00007007, 0x00003008, 0x00005009, 0x0030a00a,
};
inline constexpr Source sources[] = {
    {0x0081724a9001cd40ULL, 492, 0, 5},
    {0x01b2b542b15576baULL, 528, 5, 4},
    {0x01ee3b55014461abULL, 516, 9, 6},
    {0x02856802b906652aULL, 180, 15, 2},
    {0x030b92913e020ebaULL, 648, 17, 3},
    {0x032db7d290a070cfULL, 1284, 20, 6},
    {0x040ac080b02c2fceULL, 432, 26, 6},
    {0x052810879aa55616ULL, 888, 32, 4},
    {0x0544fc6ee839d309ULL, 540, 36, 5},
    {0x05483ef328a6a967ULL, 1020, 41, 5},
    {0x05ce419146f152beULL, 504, 46, 6},
    {0x0843f153030677caULL, 828, 52, 3},
    {0x090f98259f24c0c6ULL, 480, 55, 5},
    {0x09372df6fd539823ULL, 204, 60, 3},
    {0x0a6d1c6718545620ULL, 156, 63, 1},
    {0x0b263a3ac3611e7aULL, 552, 64, 4},
    {0x0c5ca2646fd473c6ULL, 888, 68, 8},
    {0x0d2df48e4ea40fd4ULL, 504, 76, 6},
    {0x0de518410c668aeeULL, 504, 82, 6},
    {0x0e39cb8157b514f2ULL, 888, 88, 8},
    {0x0ffcf1f11be844bfULL, 744, 96, 6},
    {0x10087292fd4f240cULL, 576, 102, 6},
    {0x1009e0b8500421fbULL, 492, 108, 6},
    {0x106d9557922f0448ULL, 708, 114, 5},
    {0x10704586ba76d247ULL, 612, 119, 3},
    {0x1154bf6d58e65a1eULL, 1104, 122, 8},
    {0x11bc08f69da45bb3ULL, 564, 130, 6},
    {0x1221be260be0afb1ULL, 492, 136, 5},
    {0x17d5a850f6325c8cULL, 540, 141, 5},
    {0x18ef88c054ed51e1ULL, 780, 146, 4},
    {0x1c8b04bfcdc3fb30ULL, 672, 150, 6},
    {0x1d350b40852511f1ULL, 912, 156, 8},
    {0x1e47084673ef9b1dULL, 816, 164, 4},
    {0x20c1c207494ddb13ULL, 192, 168, 3},
    {0x21c0c1d4ab25dc79ULL, 1080, 171, 8},
    {0x23e70d3d91afd002ULL, 492, 179, 6},
    {0x247a2ad216e0dc9bULL, 576, 185, 6},
    {0x24963fbb7c2aaaecULL, 672, 191, 3},
    {0x25ee10a5d0306f62ULL, 156, 194, 2},
    {0x26bb89631cecf5daULL, 1104, 196, 8},
    {0x28803033af01dddeULL, 108, 204, 2},
    {0x28bab8ddc352843fULL, 876, 206, 3},
    {0x2ba5952c08a8254dULL, 108, 209, 2},
    {0x2db2c4165faeaf17ULL, 636, 211, 3},
    {0x2e3131cb2e07fd1bULL, 756, 214, 4},
    {0x2ec76b40ecf1e0efULL, 516, 218, 6},
    {0x2ed2ea514fae84afULL, 348, 224, 3},
    {0x2ed7fd47c545195bULL, 564, 227, 6},
    {0x2ef573926247cf70ULL, 1056, 233, 8},
    {0x31513563f25527c0ULL, 432, 241, 4},
    {0x33651ff3f63919b8ULL, 792, 245, 8},
    {0x359f97349b52de27ULL, 564, 253, 6},
    {0x38ec4ecdd7bbd787ULL, 456, 259, 3},
    {0x3917cd48202327baULL, 504, 262, 6},
    {0x3a6b804fb7840233ULL, 432, 268, 6},
    {0x3c0fa09b7feca93cULL, 720, 274, 6},
    {0x3d5f83b107921f2fULL, 600, 280, 3},
    {0x3f4cfaf573c4b366ULL, 108, 283, 2},
    {0x4047f4f56eba67abULL, 732, 285, 8},
    {0x44c5b46a0d59c2b2ULL, 516, 293, 2},
    {0x4534af0fee562e32ULL, 552, 295, 5},
    {0x453eb2b7a0598142ULL, 180, 300, 4},
    {0x4744e624c498e24cULL, 132, 304, 2},
    {0x487f9e6ee9ec1afcULL, 1020, 306, 6},
    {0x4bb09c86187cefc4ULL, 732, 312, 5},
    {0x4f980c078f4c7066ULL, 1008, 317, 4},
    {0x4fc13c20abd207d9ULL, 684, 321, 4},
    {0x4fd2d71c0c5a345eULL, 852, 325, 5},
    {0x5000ddb8cec9c001ULL, 576, 330, 6},
    {0x501cab9f4c49b705ULL, 468, 336, 4},
    {0x529c5cf9a2beb996ULL, 504, 340, 6},
    {0x52f0e51366810a7fULL, 348, 346, 5},
    {0x532b6aae6845f749ULL, 336, 351, 5},
    {0x56677790bab31667ULL, 504, 356, 6},
    {0x5702fce723b58530ULL, 816, 362, 3},
    {0x578675ff38071caaULL, 1032, 365, 4},
    {0x57fa18014a7269d1ULL, 684, 369, 6},
    {0x58e1b7e4e859f103ULL, 468, 375, 5},
    {0x59057ff927a97aedULL, 1008, 380, 4},
    {0x59b346fd2ca4c5e7ULL, 564, 384, 6},
    {0x5b471b40a192938cULL, 1020, 390, 6},
    {0x5b7ad92302f7510eULL, 240, 396, 3},
    {0x5c571cbdd2691019ULL, 144, 399, 1},
    {0x5c6ecd0df751ec1fULL, 96, 400, 2},
    {0x5d6b5d50d05bd3b4ULL, 180, 402, 2},
    {0x5f2e4e6c6307e84dULL, 564, 404, 6},
    {0x5fc0de75b642e575ULL, 756, 410, 4},
    {0x5ff3219f76667bd3ULL, 768, 414, 5},
    {0x603c50b85514d2f3ULL, 600, 419, 3},
    {0x606c58e083f54e6dULL, 468, 422, 5},
    {0x609cbd68b34c7c20ULL, 636, 427, 4},
    {0x619faf27eb9294c2ULL, 936, 431, 8},
    {0x61d1318bccb3f2d0ULL, 1152, 439, 6},
    {0x62c79b69dc89a136ULL, 492, 445, 3},
    {0x630aa6d69074f8c5ULL, 660, 448, 4},
    {0x632b0cfd093eb2efULL, 252, 452, 3},
    {0x641e3ff6ab9ff71dULL, 144, 455, 2},
    {0x65c97a01c93ec0fdULL, 648, 457, 4},
    {0x672c9a07d52dc48fULL, 936, 461, 8},
    {0x672d1721adf484b3ULL, 636, 469, 3},
    {0x67cc9a6122a4116fULL, 720, 472, 5},
    {0x6834808299a9f391ULL, 756, 477, 5},
    {0x68d5f2d5347815dcULL, 840, 482, 6},
    {0x68e25773167daf55ULL, 252, 488, 2},
    {0x69d5da61d244b905ULL, 540, 490, 3},
    {0x6a97a4a61766257fULL, 564, 493, 4},
    {0x6af8842a11e468d3ULL, 732, 497, 4},
    {0x6b8d37191d113e57ULL, 120, 501, 2},
    {0x6b9322449279615cULL, 612, 503, 3},
    {0x6df3276363d039edULL, 852, 506, 5},
    {0x6f28131df072f1c1ULL, 396, 511, 6},
    {0x71d85ebd63780c7cULL, 84, 517, 1},
    {0x722566a3d12cbd2fULL, 720, 518, 6},
    {0x729b846e9a4d320cULL, 864, 524, 4},
    {0x7348ba091da3d087ULL, 816, 528, 4},
    {0x73a2490230625073ULL, 792, 532, 5},
    {0x7440512349edd030ULL, 840, 537, 5},
    {0x768b9791817bfd40ULL, 432, 542, 6},
    {0x78c254fe341ef9a9ULL, 540, 548, 3},
    {0x7bc420e871c3feccULL, 132, 551, 2},
    {0x7f1d497ee2855d44ULL, 672, 553, 3},
    {0x7fe46a8490fd96c7ULL, 792, 556, 4},
    {0x805b21f3de3d082dULL, 240, 560, 2},
    {0x8118bba7dc1308bbULL, 672, 562, 3},
    {0x81f19b99bb59f1e7ULL, 696, 565, 4},
    {0x82f949746009c372ULL, 96, 569, 2},
    {0x836998c81806b82aULL, 384, 571, 4},
    {0x8531523423acca28ULL, 672, 575, 4},
    {0x86b6d4431047c9d2ULL, 360, 579, 4},
    {0x875a7e2df3065732ULL, 204, 583, 4},
    {0x87d1a60cfa5bf202ULL, 612, 587, 4},
    {0x87e01d308c004700ULL, 804, 591, 6},
    {0x891495a8075c26d1ULL, 588, 597, 5},
    {0x8af0eb5782bd0998ULL, 684, 602, 4},
    {0x8b308f4a28db1ad2ULL, 504, 606, 6},
    {0x8b3aa684d77d562aULL, 948, 612, 8},
    {0x8d278e8d170bed87ULL, 516, 620, 4},
    {0x8f2dd79fe4531e32ULL, 1092, 624, 4},
    {0x8fb018bf9002803eULL, 552, 628, 5},
    {0x92310e4cba5ba743ULL, 708, 633, 5},
    {0x931d4d95c8e57cdaULL, 564, 638, 4},
    {0x932912555c1669f5ULL, 228, 642, 2},
    {0x9513f083e23dbb96ULL, 444, 644, 6},
    {0x951dee4bed2d2973ULL, 504, 650, 6},
    {0x95279cdeb7210fbaULL, 876, 656, 6},
    {0x96c722fb41c9d0afULL, 132, 662, 1},
    {0x981204bab5e460f8ULL, 132, 663, 2},
    {0x984e2a862388561cULL, 720, 665, 5},
    {0x9973159d69f8ed11ULL, 384, 670, 5},
    {0x9c79a449417c8d2aULL, 684, 675, 4},
    {0x9ce12d2433b05f99ULL, 552, 679, 5},
    {0x9d0e753daf8dbfd7ULL, 876, 684, 4},
    {0x9e88a5d02c65a3a1ULL, 996, 688, 6},
    {0x9f1525fbccf2660fULL, 408, 694, 5},
    {0x9fe359032a9ec04cULL, 828, 699, 6},
    {0xa19c4aef51dded25ULL, 528, 705, 3},
    {0xa49287e4db6d4b8dULL, 168, 708, 2},
    {0xa623d94be43e15e4ULL, 204, 710, 1},
    {0xa6e58516a634514cULL, 744, 711, 8},
    {0xa70899e96f1186b6ULL, 1224, 719, 8},
    {0xa823c3b89bcee5dfULL, 360, 727, 3},
    {0xa834cd5fd9d1c712ULL, 1020, 730, 5},
    {0xacca3581ea53e78eULL, 192, 735, 2},
    {0xad55c690d80b0ec9ULL, 660, 737, 3},
    {0xadc92d339da43bd6ULL, 576, 740, 6},
    {0xaf544d9e4bd5d099ULL, 96, 746, 2},
    {0xaf885878259e2dbcULL, 180, 748, 2},
    {0xb0135bbf29f355faULL, 792, 750, 8},
    {0xb0d956aaa3879f03ULL, 792, 758, 5},
    {0xb282c9dc76bef86aULL, 864, 763, 4},
    {0xb30170b619fc5e78ULL, 468, 767, 5},
    {0xb3828e52bf7d5fd1ULL, 492, 772, 3},
    {0xb39d7ae6025ed9b3ULL, 840, 775, 4},
    {0xb7295451b22b6738ULL, 492, 779, 6},
    {0xb83b9bc283b1ca08ULL, 156, 785, 1},
    {0xb86cfae7c3753619ULL, 696, 786, 5},
    {0xbb16d627db31c722ULL, 504, 791, 6},
    {0xbecdcbdf39c30c42ULL, 360, 797, 6},
    {0xbf92a1aa891b2191ULL, 384, 803, 5},
    {0xc09325900e8e9226ULL, 540, 808, 3},
    {0xc2809cc4810b661dULL, 228, 811, 2},
    {0xc2da3c560804d551ULL, 216, 813, 3},
    {0xc3fcaf8d9eee036dULL, 864, 816, 6},
    {0xc42596d228189bb7ULL, 564, 822, 6},
    {0xc44542f11b995cb5ULL, 876, 828, 5},
    {0xc48669df6cf991d1ULL, 396, 833, 3},
    {0xc5b2415302f9f999ULL, 336, 836, 5},
    {0xc7dadaeb83055178ULL, 1068, 841, 4},
    {0xc88c3e600dea7500ULL, 900, 845, 8},
    {0xc8ac144c362cb871ULL, 804, 853, 6},
    {0xc979acd98f36e67eULL, 432, 859, 6},
    {0xc9e74f2ba401d6c1ULL, 696, 865, 5},
    {0xcb20dcc130726520ULL, 876, 870, 5},
    {0xcb75673123d31dc5ULL, 492, 875, 5},
    {0xcc3cca38ccd919f8ULL, 540, 880, 5},
    {0xccd14315be8cc74bULL, 816, 885, 6},
    {0xcd6da22526d53c78ULL, 1008, 891, 6},
    {0xcdfa8474b59541b8ULL, 492, 897, 6},
    {0xcf62b979cdce5404ULL, 456, 903, 3},
    {0xcf89c3ac97b2f36cULL, 720, 906, 5},
    {0xd1362c7d3256a8c8ULL, 612, 911, 3},
    {0xd1e3124205e7669eULL, 408, 914, 6},
    {0xd3d3d0c82a0a1b97ULL, 480, 920, 5},
    {0xd4d38aee7371cae2ULL, 480, 925, 3},
    {0xd534397a967bf32aULL, 792, 928, 8},
    {0xd5f57621120cff9eULL, 624, 936, 3},
    {0xd6680fe830073d16ULL, 492, 939, 5},
    {0xd71283cda5041071ULL, 216, 944, 3},
    {0xd815e082585a71b0ULL, 732, 947, 4},
    {0xd84c0386298e0c8cULL, 456, 951, 4},
    {0xda91bf0785fd0e1bULL, 324, 955, 6},
    {0xdb17848f44742994ULL, 936, 961, 4},
    {0xdc58aaf32a4562c2ULL, 828, 965, 5},
    {0xdc6552ef6ac79d2fULL, 864, 970, 6},
    {0xde0c724cef7bb3f6ULL, 564, 976, 3},
    {0xde3ed701839f09b1ULL, 132, 979, 2},
    {0xdf230af5c98dc73fULL, 840, 981, 4},
    {0xdfdfd809d424efa5ULL, 972, 985, 5},
    {0xe0da8162972a1164ULL, 756, 990, 3},
    {0xe3b4043dd754f28cULL, 372, 993, 5},
    {0xe40b1b41ab5e8387ULL, 552, 998, 3},
    {0xe6ea1e0bab8c539aULL, 480, 1001, 5},
    {0xe77cd4522abcef0bULL, 1248, 1006, 8},
    {0xe7c0d16f6570d6e6ULL, 516, 1014, 3},
    {0xe82aa5a9ae62bbdcULL, 372, 1017, 6},
    {0xe98d83edafe0096eULL, 204, 1023, 3},
    {0xebce3d052405984cULL, 576, 1026, 4},
    {0xec4cf615564978d4ULL, 1020, 1030, 5},
    {0xedfa90319e261f83ULL, 948, 1035, 4},
    {0xee391b30b8634008ULL, 792, 1039, 4},
    {0xefb7faf06a9f1e02ULL, 408, 1043, 5},
    {0xf099a880607a0bd2ULL, 312, 1048, 4},
    {0xf12dce3b08b173efULL, 408, 1052, 5},
    {0xf22ca31193c52d59ULL, 612, 1057, 4},
    {0xf31d3268877c9502ULL, 108, 1061, 1},
    {0xf3ca472a261d9b34ULL, 816, 1062, 5},
    {0xf441f03eb43a8733ULL, 816, 1067, 4},
    {0xf48f81168af6e75fULL, 204, 1071, 3},
    {0xfa389b549ec6eb60ULL, 576, 1074, 4},
    {0xfa891413020dac49ULL, 780, 1078, 5},
    {0xfbc19b92d9ef4042ULL, 252, 1083, 3},
    {0xfbc7890024ac7ff8ULL, 744, 1086, 3},
    {0xfeb1daad7b5e92dbULL, 576, 1089, 6},
    {0xfeed2f790be1ab5dULL, 96, 1095, 2},
    {0xfef6e9d06d85601cULL, 504, 1097, 6},
};
// END GENERATED METADATA

inline uint64_t Hash(std::span<const uint8_t> bytes) {
    uint64_t hash = 0xcbf29ce484222325ULL;
    for (const auto byte : bytes) hash = (hash ^ byte) * 0x100000001b3ULL;
    return hash;
}
inline std::string Name(uint64_t hash) {
    std::string name = "vs_0000000000000000.bin";
    constexpr char digits[] = "0123456789abcdef";
    for (size_t i = 0; i < 16; ++i) {
        name[18 - i] = digits[hash & 15];
        hash >>= 4;
    }
    return name;
}
inline uint32_t ReadBE(const uint8_t* bytes) {
    return uint32_t(bytes[0]) << 24 | uint32_t(bytes[1]) << 16 |
           uint32_t(bytes[2]) << 8 | bytes[3];
}
inline void WriteBE(uint8_t* bytes, uint32_t word) {
    for (unsigned i = 0; i < 4; ++i) bytes[i] = uint8_t(word >> (24 - i * 8));
}
constexpr const Element* FindElement(const Declaration& declaration, uint32_t metadata) {
    for (size_t i = declaration.first; i < size_t(declaration.first) + declaration.count; ++i) {
        const auto& element = elements[i];
        if (element.usage == ((metadata >> 12) & 15) && element.index == ((metadata >> 16) & 15))
            return &element;
    }
    return nullptr;
}
consteval bool ValidMetadata() {
    for (const auto& declaration : declarations) {
        if (!declaration.count || size_t(declaration.first) + declaration.count > std::size(elements) ||
            !declaration.extent || declaration.extent > 252) return false;
        for (size_t i = declaration.first; i < size_t(declaration.first) + declaration.count; ++i) {
            const auto& element = elements[i];
            const auto width = widths[element.format & 63];
            if (element.stream != 0 || element.offset % 4 || !width ||
                element.offset / 4 + width > declaration.extent ||
                (element.format & 0xc0) == 0x40) return false;
        }
    }
    for (const auto& source : sources) {
        if (source.size < 12 || source.size > 262144 || source.size % 12 || !source.count ||
            size_t(source.first) + source.count > std::size(fetchMetadata)) return false;
        for (size_t i = source.first; i < size_t(source.first) + source.count; ++i) {
            if (uint64_t(fetchMetadata[i] & 4095) * 12 + 12 > source.size) return false;
            for (size_t j = source.first; j < i; ++j)
                if ((fetchMetadata[i] & 4095) == (fetchMetadata[j] & 4095)) return false;
        }
    }
    return true;
}
static_assert(ValidMetadata(), "invalid fixed shader variant metadata");

using Fetch = std::array<uint32_t, 3>;
// Matching-declaration branch of SDK 0x823F2960. Unsupported byte-order
// swizzles are rejected by the metadata validator, not approximated here.
inline Fetch PatchFetch(Fetch original, const Element& element) {
    const auto type = element.format;
    uint32_t swizzle = (((type >> 10) & 0x38) | ((type >> 16) & 7)) << 3 | ((type >> 19) & 7);
    swizzle = ((swizzle << 1) | (type & 0x1c00)) << 3;
    const auto format = (((type & 0x3f) << 12) | (type & 0x300)) << 4 | (original[1] & 0xbfc0cfff);
    const uint32_t stream = (0x5f - element.stream) * 0x1560056u;
    const auto word0 = (((stream & 0x1f00) << 11) | (stream & 0x3000000)) << 1 |
                       (original[0] & 0xc00fffff);
    const auto word2 = uint32_t(element.offset & 0x1fffffc) << 6 | (original[2] & 0x80000000);
    swizzle |= 14;
    const auto a = swizzle & swizzleMasks[format & 7];
    const auto b = swizzle & swizzleMasks[(format >> 3) & 7];
    const auto c = swizzle & swizzleMasks[(format >> 6) & 7];
    const auto d = swizzle & swizzleMasks[(format >> 9) & 7];
    uint32_t word1 = (((((((a >> 3) | a) >> 3 | a) >> 3 | a) >> 3 | a) >> 1) & 7) |
                     (format & 0xfffff000);
    word1 |= ((((((b >> 3) | b) >> 3 | b) >> 3 | b) >> 1) | (b << 2)) & 0x38;
    word1 |= (((((c >> 3) | c) >> 3 | c) >> 1) | ((c << 3 | c) << 2)) & 0x1c0;
    word1 |= ((((d << 3 | d) << 3 | d) << 2) | ((d >> 3 | d) >> 1)) & 0xe00;
    return {word0, word1, word2};
}
inline unsigned Stream(const Fetch& fetch) { return ((fetch[0] >> 18) & 0x7c) | ((fetch[0] >> 25) & 3); }
inline int32_t Offset(const Fetch& fetch) {
    int32_t value = int32_t((fetch[2] >> 8) & 0x7fffff);
    return value & 0x400000 ? value - 0x800000 : value;
}
inline int32_t Width(const Fetch& fetch) { return widths[(fetch[1] >> 16) & 63]; }
// Preserve compiler-defined groups and the SDK's reserved final fetch stream.
inline void Prefetch(std::span<const uint32_t> metadata, std::vector<Fetch>& fetches) {
    size_t start = 0;
    while (start < metadata.size()) {
        while (start < metadata.size() && !(metadata[start] & 0x300000)) ++start;
        if (start == metadata.size()) break;
        size_t end = start + 1;
        while (end < metadata.size() && !(metadata[end] & 0x300000)) ++end;
        if (end == metadata.size()) break;
        const bool hasReserved = (metadata[end] & 0x300000) == 0x300000;
        const auto reserved = Stream(fetches[end]);
        const size_t last = hasReserved ? end : end + 1;
        std::stable_sort(fetches.begin() + start, fetches.begin() + last,
            [=](const Fetch& a, const Fetch& b) {
                const auto sa = Stream(a), sb = Stream(b);
                if (sa == sb) return Offset(a) == Offset(b) ? Width(a) < Width(b) : Offset(a) < Offset(b);
                if (hasReserved && sa == reserved) return false;
                if (hasReserved && sb == reserved) return true;
                return sa > sb;
            });
        size_t previous = start;
        for (size_t j = start + 1; j <= end; ++j) {
            auto& a = fetches[previous];
            auto& b = fetches[j];
            const auto streamA = ((a[0] >> 7) & 0xc0000) | (a[0] & 0x1f00000);
            const auto streamB = ((b[0] >> 7) & 0xc0000) | (b[0] & 0x1f00000);
            const auto extent = Width(b) - Offset(a) + Offset(b);
            if (streamA == streamB && Offset(a) <= Offset(b) && extent < 9) {
                const auto span = std::max(extent - 1, int32_t((a[0] >> 27) & 7));
                a[0] = (a[0] & 0xc7ffffff) | uint32_t(span & 7) << 27;
                b[1] |= 0x40000000;
            } else previous = j;
        }
        start = end + 1;
    }
}
} // namespace detail

// Returns 1 for valid bytes, 0 for missing, -1 for invalid. The caller owns code.
using SourceReader = std::function<int(uint64_t, uint32_t, bool, std::vector<uint8_t>&)>;

struct FixedVariantResult {
    size_t verifiedBases = 0, missingBases = 0, invalidBases = 0, generated = 0;
    uint64_t bytesRead = 0;
    bool cancelled = false;
};

// Reads only known source names, validates exact length and the original code
// hash, then generates fixed-declaration candidates. It does not alias shader
// hashes or alter a draw's shader. Packed and 16-byte-aligned stream extents are
// bounded layout candidates, not a claim that all combinations are used.
// save is synchronous; its span expires when it returns. Save exceptions propagate.
inline FixedVariantResult GenerateFixedVariants(
    const std::filesystem::path& sourceDirectory,
    const std::function<void(uint64_t, std::span<const uint8_t>)>& save,
    const std::function<bool()>& cancelled = {}, const SourceReader& readSource = {}) {
    if (!save) throw std::invalid_argument("fixed shader variants require a save callback");
    FixedVariantResult result;
    std::set<uint64_t> emitted;
    for (const auto& source : detail::sources) {
        if (cancelled && cancelled()) { result.cancelled = true; break; }
        std::vector<uint8_t> code;
        if (readSource) {
            const int status = readSource(source.hash, source.size, false, code);
            if (status == 0) { ++result.missingBases; continue; }
            if (status != 1 || code.size() != source.size || detail::Hash(code) != source.hash) {
                ++result.invalidBases; continue;
            }
        } else {
        std::ifstream in(sourceDirectory / detail::Name(source.hash), std::ios::binary | std::ios::ate);
        if (!in) { ++result.missingBases; continue; }
        if (in.tellg() != std::streamoff(source.size)) { ++result.invalidBases; continue; }
        code.resize(source.size);
        in.seekg(0);
        in.read(reinterpret_cast<char*>(code.data()), std::streamsize(code.size()));
        result.bytesRead += uint64_t(in.gcount());
        if (!in || in.peek() != std::char_traits<char>::eof() || detail::Hash(code) != source.hash) {
            ++result.invalidBases;
            continue;
        }
        }
        ++result.verifiedBases;
        const auto metadata = std::span(detail::fetchMetadata).subspan(source.first, source.count);
        for (const auto& declaration : detail::declarations) {
            std::vector<detail::Fetch> fetches;
            for (const auto elementMetadata : metadata) {
                const auto* element = detail::FindElement(declaration, elementMetadata);
                if (!element) break;
                const auto* input = code.data() + size_t(elementMetadata & 4095) * 12;
                fetches.push_back(detail::PatchFetch(
                    {detail::ReadBE(input), detail::ReadBE(input + 4), detail::ReadBE(input + 8)}, *element));
            }
            if (fetches.size() != metadata.size()) continue;
            detail::Prefetch(metadata, fetches);
            const unsigned strides[] = {declaration.extent, unsigned((declaration.extent + 3) & ~3)};
            for (unsigned strideIndex = 0; strideIndex < 2; ++strideIndex) {
                if (strideIndex && strides[0] == strides[1]) continue;
                if (cancelled && cancelled()) { result.cancelled = true; return result; }
                auto patched = code;
                for (size_t i = 0; i < metadata.size(); ++i) {
                    auto* output = patched.data() + size_t(metadata[i] & 4095) * 12;
                    detail::WriteBE(output, fetches[i][0]);
                    detail::WriteBE(output + 4, fetches[i][1]);
                    detail::WriteBE(output + 8, (fetches[i][2] & ~255u) | strides[strideIndex]);
                }
                const auto hash = detail::Hash(patched);
                if (emitted.insert(hash).second) {
                    save(hash, patched);
                    ++result.generated;
                }
            }
        }
    }
    return result;
}

struct LinkedVariantResult : FixedVariantResult {
    size_t verifiedPixelSources = 0, missingPixelSources = 0, invalidPixelSources = 0;
};

namespace detail {
consteval bool ValidLinkMetadata() {
    for (const auto& pixel : link::pixels)
        if (pixel.size < 12 || pixel.size > 262144 || pixel.size % 12) return false;
    for (const auto& plan : link::plans) {
        if (plan.source >= std::size(sources) ||
            (plan.pixel != 65535 && plan.pixel >= std::size(link::pixels)) ||
            size_t(plan.first) + plan.count > std::size(link::edits)) return false;
        for (size_t i = plan.first; i < size_t(plan.first) + plan.count; ++i) {
            const auto& edit = link::edits[i];
            if (uint64_t(edit.instruction) * 12 + 12 > sources[plan.source].size ||
                (edit.output > 15 && edit.output != 255)) return false;
        }
    }
    return true;
}
static_assert(ValidLinkMetadata(), "invalid original SDK shader link metadata");
} // namespace detail

// Additional variants from original SDK VS/PS output-link metadata. The source
// shader and representative PS are hash-checked before using a plan. Plans are
// metadata derived from source semantics and patch lists, not observed shaders.
// Existing fixed candidates are excluded; no shader identity is substituted.
inline LinkedVariantResult GenerateLinkedVariants(
    const std::filesystem::path& sourceDirectory,
    const std::function<void(uint64_t, std::span<const uint8_t>)>& save,
    const std::function<bool()>& cancelled = {}, const SourceReader& readSource = {},
    const std::set<uint64_t>* fixedHashes = nullptr) {
    if (!save) throw std::invalid_argument("linked shader variants require a save callback");
    LinkedVariantResult result;
    std::set<uint64_t> emitted;
    if (fixedHashes) emitted = *fixedHashes;
    else {
        const auto fixed = GenerateFixedVariants(sourceDirectory,
            [&](uint64_t hash, auto) { emitted.insert(hash); }, cancelled, readSource);
        result.bytesRead = fixed.bytesRead;
        if (fixed.cancelled) { result.cancelled = true; return result; }
    }
    auto read = [&](uint64_t hash, uint32_t size, bool pixel, std::vector<uint8_t>& code) {
        if (readSource) {
            const int status = readSource(hash, size, pixel, code);
            if (status != 1) return status;
            return code.size() == size && detail::Hash(code) == hash ? 1 : -1;
        }
        auto name = detail::Name(hash);
        if (pixel) name[0] = 'p';
        std::ifstream in(sourceDirectory / name, std::ios::binary | std::ios::ate);
        if (!in) return 0; // missing
        if (in.tellg() != std::streamoff(size)) return -1;
        code.resize(size);
        in.seekg(0);
        in.read(reinterpret_cast<char*>(code.data()), std::streamsize(code.size()));
        result.bytesRead += uint64_t(in.gcount());
        return in && in.peek() == std::char_traits<char>::eof() && detail::Hash(code) == hash ? 1 : -1;
    };
    std::array<bool, std::size(detail::link::pixels)> pixels{};
    for (size_t i = 0; i < pixels.size(); ++i) {
        if (cancelled && cancelled()) { result.cancelled = true; return result; }
        const auto& pixel = detail::link::pixels[i];
        std::vector<uint8_t> bytes;
        const auto status = read(pixel.hash, pixel.size, true, bytes);
        pixels[i] = status == 1;
        if (status == 1) ++result.verifiedPixelSources;
        else if (status == 0) ++result.missingPixelSources;
        else ++result.invalidPixelSources;
    }
    for (size_t sourceIndex = 0; sourceIndex < std::size(detail::sources); ++sourceIndex) {
        if (cancelled && cancelled()) { result.cancelled = true; return result; }
        const auto& source = detail::sources[sourceIndex];
        std::vector<uint8_t> code;
        const auto status = read(source.hash, source.size, false, code);
        if (status != 1) {
            if (status == 0) ++result.missingBases; else ++result.invalidBases;
            continue;
        }
        ++result.verifiedBases;
        const auto metadata = std::span(detail::fetchMetadata).subspan(source.first, source.count);
        for (const auto& declaration : detail::declarations) {
            std::vector<detail::Fetch> fetches;
            for (const auto elementMetadata : metadata) {
                const auto* element = detail::FindElement(declaration, elementMetadata);
                if (!element) break;
                const auto* input = code.data() + size_t(elementMetadata & 4095) * 12;
                fetches.push_back(detail::PatchFetch(
                    {detail::ReadBE(input), detail::ReadBE(input + 4), detail::ReadBE(input + 8)}, *element));
            }
            if (fetches.size() != metadata.size()) continue;
            detail::Prefetch(metadata, fetches);
            for (const auto& plan : detail::link::plans) {
                if (plan.source != sourceIndex || (plan.pixel != 65535 && !pixels[plan.pixel])) continue;
                auto linked = code;
                for (size_t i = plan.first; i < size_t(plan.first) + plan.count; ++i) {
                    const auto& edit = detail::link::edits[i];
                    auto* instruction = linked.data() + size_t(edit.instruction) * 12;
                    if (edit.output == 255) {
                        // Original SDK output deletion instruction, not title microcode.
                        detail::WriteBE(instruction, 0xc8000000);
                        detail::WriteBE(instruction + 4, 0);
                        detail::WriteBE(instruction + 8, 0x02000000);
                    } else detail::WriteBE(instruction, (detail::ReadBE(instruction) & ~15u) | edit.output);
                }
                const unsigned strides[] = {declaration.extent, unsigned((declaration.extent + 3) & ~3)};
                for (unsigned strideIndex = 0; strideIndex < 2; ++strideIndex) {
                    if (strideIndex && strides[0] == strides[1]) continue;
                    if (cancelled && cancelled()) { result.cancelled = true; return result; }
                    auto patched = linked;
                    for (size_t i = 0; i < metadata.size(); ++i) {
                        auto* output = patched.data() + size_t(metadata[i] & 4095) * 12;
                        detail::WriteBE(output, fetches[i][0]);
                        detail::WriteBE(output + 4, fetches[i][1]);
                        detail::WriteBE(output + 8, (fetches[i][2] & ~255u) | strides[strideIndex]);
                    }
                    const auto hash = detail::Hash(patched);
                    if (emitted.insert(hash).second) { save(hash, patched); ++result.generated; }
                }
            }
        }
    }
    return result;
}
} // namespace xenos::resources::variants
