#pragma once

#include "resource_variant_links.h"

#include <algorithm>
#include <array>
#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <functional>
#include <set>
#include <span>
#include <stdexcept>
#include <string>
#include <vector>

namespace xenos::resources::variants {
namespace detail {
struct Element {
    uint32_t format;
    uint16_t offset;
    uint8_t stream, usage, index;
};
struct Declaration {
    uint16_t first;
    uint8_t count, extent;
};
struct Source {
    uint64_t hash;
    uint32_t size;
    uint16_t first, count;
};

// BEGIN GENERATED METADATA
// Generated by tools/generate_shader_variants.py. Metadata only; no microcode.
// Original XEX image SHA256: cb756b46092e448923517bf660b44ad1a0651c2860882b43ae021f4ad4290f71
// SDK width table 0x82216538; component swizzle masks 0x82185A40.
inline constexpr uint8_t widths[] = {
    0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 1,
    2, 1, 2, 4, 1, 2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0,
};
inline constexpr uint16_t swizzleMasks[] = {
    0xe000, 0x1c00, 0x0380, 0x0070, 0x0008, 0x000a, 0x0008, 0x000e
};
inline constexpr Element elements[] = {
    {0x002a23b9, 0, 0, 0, 0},
    {0x002a23b9, 12, 0, 3, 0},
    {0x002a23b9, 24, 0, 6, 0},
    {0x002c23a5, 36, 0, 5, 0},
    {0x002c83a4, 44, 0, 1, 0},
    {0x001a23a6, 48, 0, 5, 3},
    {0x002c23a5, 64, 0, 5, 1},
    {0x001a23a6, 72, 0, 5, 2},
    {0x002a23b9, 0, 0, 0, 0},
    {0x002a23b9, 12, 0, 3, 0},
    {0x002a23b9, 24, 0, 6, 0},
    {0x002c23a5, 36, 0, 5, 0},
    {0x002c83a4, 44, 0, 1, 0},
    {0x001a23a6, 48, 0, 5, 1},
    {0x002a23b9, 0, 0, 0, 0},
    {0x001a23a6, 0, 0, 0, 0},
    {0x002c23a5, 16, 0, 5, 0},
    {0x001a23a6, 24, 0, 10, 0},
    {0x00182886, 40, 0, 10, 1},
    {0x001a23a6, 0, 0, 0, 0},
    {0x002c23a5, 16, 0, 5, 0},
    {0x002c23a5, 0, 0, 0, 0},
    {0x002c23a5, 0, 0, 0, 0},
    {0x002c23a5, 8, 0, 5, 0},
    {0x002a23b9, 0, 0, 0, 0},
    {0x002a23b9, 12, 0, 3, 0},
    {0x002a23b9, 24, 0, 6, 0},
    {0x002c23a5, 36, 0, 5, 0},
    {0x002c83a4, 44, 0, 1, 0},
    {0x001a23a6, 48, 0, 5, 1},
};
inline constexpr Declaration declarations[] = {
    {0, 8, 22}, // Original constructor 0x823B8848
    {8, 6, 16}, // Original constructor 0x823B8B70
    {14, 1, 3}, // Original constructor 0x824980E8
    {15, 4, 11}, // Original constructor 0x82555510
    {19, 2, 6}, // Original constructor 0x825CDB08
    {21, 1, 2}, // Original constructor 0x82763DE0
    {22, 2, 4}, // Original constructor 0x827A0CC8
    {24, 6, 16}, // Original constructor 0x827A3928
};
inline constexpr uint32_t fetchMetadata[] = {
    0x00100003, 0x00305004, 0x00100008, 0x00003009, 0x0000500a, 0x0000100b, 0x0021500c, 0x00100003,
    0x00005004, 0x00215005, 0x00100005, 0x00003006, 0x00005007, 0x00215008, 0x00100008, 0x00003009,
    0x0000600a, 0x0000500b, 0x0000100c, 0x0001500d, 0x0002500e, 0x0023500f, 0x00100009, 0x0000300a,
    0x0000600b, 0x0000500c, 0x0000100d, 0x0001500e, 0x0002500f, 0x00235010, 0x00100006, 0x00003007,
    0x00006008, 0x00005009, 0x0000100a, 0x0021500b, 0x00100008, 0x00003009, 0x0000600a, 0x0000500b,
    0x0000100c, 0x0001500d, 0x0002500e, 0x0023500f, 0x00100003, 0x00005004, 0x00215005, 0x00100009,
    0x0000300a, 0x0000600b, 0x0000500c, 0x0000100d, 0x0001500e, 0x0002500f, 0x00235010, 0x00100003,
    0x00305004, 0x00100009, 0x0000300a, 0x0000600b, 0x0000500c, 0x0000100d, 0x0001500e, 0x0002500f,
    0x00235010, 0x00100003, 0x00305004, 0x00100003, 0x00305004, 0x00100008, 0x00003009, 0x0000600a,
    0x0000500b, 0x0000100c, 0x0001500d, 0x0002500e, 0x0023500f, 0x00100007, 0x00003008, 0x00006009,
    0x0000500a, 0x0000100b, 0x0001500c, 0x0002500d, 0x0023500e, 0x00100006, 0x00003007, 0x00006008,
    0x00005009, 0x0000100a, 0x0021500b, 0x00100003, 0x00205004, 0x00100006, 0x00003007, 0x00006008,
    0x00005009, 0x0000100a, 0x0001500b, 0x0002500c, 0x0023500d, 0x00100003, 0x00005004, 0x0000a005,
    0x0031a006, 0x00100003, 0x00205004, 0x00100008, 0x00003009, 0x0000600a, 0x0000500b, 0x0000100c,
    0x0021500d, 0x00100006, 0x00003007, 0x00005008, 0x00001009, 0x0021500a, 0x00100006, 0x00003007,
    0x00006008, 0x00005009, 0x0000100a, 0x0021500b, 0x00100008, 0x00003009, 0x0000600a, 0x0000500b,
    0x0000100c, 0x0021500d, 0x00100003, 0x00005004, 0x00215005, 0x00000003, 0x00100003, 0x00305004,
    0x00100003, 0x00305004, 0x00100009, 0x0000300a, 0x0000600b, 0x0000500c, 0x0000100d, 0x0021500e,
    0x00100003, 0x00005004, 0x0030a005, 0x00100003, 0x00305004, 0x00100008, 0x00003009, 0x0000600a,
    0x0000500b, 0x0000100c, 0x0001500d, 0x0002500e, 0x0023500f, 0x00100006, 0x00003007, 0x00005008,
    0x00001009, 0x0021500a, 0x00100007, 0x00003008, 0x00006009, 0x0000500a, 0x0000100b, 0x0021500c,
    0x00100004, 0x00205005, 0x00100005, 0x00003006, 0x00205007, 0x00100003, 0x00305004, 0x00100006,
    0x00005007, 0x0020a008, 0x00100007, 0x00003008, 0x00005009, 0x0000100a, 0x0021500b, 0x00000003,
    0x00100007, 0x00003008, 0x00005009, 0x0000100a, 0x0021500b, 0x00100003, 0x00205004, 0x00100003,
    0x00205004, 0x00100003, 0x00305004, 0x00100003, 0x00005004, 0x0000a005, 0x0031a006, 0x00100006,
    0x00003007, 0x00005008, 0x00015009, 0x0022500a, 0x00100008, 0x00003009, 0x0000600a, 0x0000500b,
    0x0000100c, 0x0001500d, 0x0002500e, 0x0023500f, 0x00100006, 0x00003007, 0x00005008, 0x00001009,
    0x0021500a, 0x00100003, 0x00305004, 0x00100007, 0x00003008, 0x00006009, 0x0000500a, 0x0000100b,
    0x0021500c, 0x00000003, 0x00100003, 0x00305004, 0x00100008, 0x00003009, 0x0000600a, 0x0000500b,
    0x0000100c, 0x0021500d, 0x00100003, 0x00305004, 0x00100006, 0x00003007, 0x00006008, 0x00005009,
    0x0000100a, 0x0001500b, 0x0002500c, 0x0023500d, 0x0010000a, 0x0000300b, 0x0000600c, 0x0000500d,
    0x0000100e, 0x0001500f, 0x00025010, 0x00235011, 0x00100003, 0x00205004, 0x00100003, 0x00305004,
    0x00100007, 0x00003008, 0x00006009, 0x0000500a, 0x0000100b, 0x0001500c, 0x0002500d, 0x0023500e,
    0x00000003, 0x00100003, 0x00005004, 0x0020a005, 0x00100007, 0x00003008, 0x00005009, 0x0000100a,
    0x0021500b, 0x00100006, 0x00003007, 0x00006008, 0x00005009, 0x0000100a, 0x0021500b, 0x00100008,
    0x00003009, 0x0000600a, 0x0000500b, 0x0000100c, 0x0021500d, 0x00100007, 0x00003008, 0x00006009,
    0x0000500a, 0x0000100b, 0x0001500c, 0x0002500d, 0x0023500e, 0x00100003, 0x00005004, 0x00215005,
    0x00100007, 0x00003008, 0x00006009, 0x0000500a, 0x0000100b, 0x0021500c, 0x00100003, 0x00305004,
    0x00100003, 0x00005004, 0x00315005, 0x00100008, 0x00003009, 0x0000500a, 0x0000100b, 0x0021500c,
    0x00000003, 0x00100007, 0x00003008, 0x00005009, 0x0000100a, 0x0021500b, 0x00100003, 0x00005004,
    0x0030a005, 0x00100007, 0x00003008, 0x00005009, 0x0000100a, 0x0021500b, 0x00100003, 0x00005004,
    0x00315005, 0x00100003, 0x00305004,
};
inline constexpr Source sources[] = {
    {0x02856802b906652aULL, 180, 0, 2},
    {0x05483ef328a6a967ULL, 1020, 2, 5},
    {0x09372df6fd539823ULL, 204, 7, 3},
    {0x0b263a3ac3611e7aULL, 552, 10, 4},
    {0x0c5ca2646fd473c6ULL, 888, 14, 8},
    {0x1154bf6d58e65a1eULL, 1104, 22, 8},
    {0x1c8b04bfcdc3fb30ULL, 672, 30, 6},
    {0x1d350b40852511f1ULL, 912, 36, 8},
    {0x20c1c207494ddb13ULL, 192, 44, 3},
    {0x21c0c1d4ab25dc79ULL, 1080, 47, 8},
    {0x25ee10a5d0306f62ULL, 156, 55, 2},
    {0x26bb89631cecf5daULL, 1104, 57, 8},
    {0x28803033af01dddeULL, 108, 65, 2},
    {0x2ba5952c08a8254dULL, 108, 67, 2},
    {0x2ef573926247cf70ULL, 1056, 69, 8},
    {0x33651ff3f63919b8ULL, 792, 77, 8},
    {0x3c0fa09b7feca93cULL, 720, 85, 6},
    {0x3f4cfaf573c4b366ULL, 108, 91, 2},
    {0x4047f4f56eba67abULL, 732, 93, 8},
    {0x453eb2b7a0598142ULL, 180, 101, 4},
    {0x4744e624c498e24cULL, 132, 105, 2},
    {0x487f9e6ee9ec1afcULL, 1020, 107, 6},
    {0x4bb09c86187cefc4ULL, 732, 113, 5},
    {0x57fa18014a7269d1ULL, 684, 118, 6},
    {0x5b471b40a192938cULL, 1020, 124, 6},
    {0x5b7ad92302f7510eULL, 240, 130, 3},
    {0x5c571cbdd2691019ULL, 144, 133, 1},
    {0x5c6ecd0df751ec1fULL, 96, 134, 2},
    {0x5d6b5d50d05bd3b4ULL, 180, 136, 2},
    {0x61d1318bccb3f2d0ULL, 1152, 138, 6},
    {0x632b0cfd093eb2efULL, 252, 144, 3},
    {0x641e3ff6ab9ff71dULL, 144, 147, 2},
    {0x672c9a07d52dc48fULL, 936, 149, 8},
    {0x6834808299a9f391ULL, 756, 157, 5},
    {0x68d5f2d5347815dcULL, 840, 162, 6},
    {0x68e25773167daf55ULL, 252, 168, 2},
    {0x69d5da61d244b905ULL, 540, 170, 3},
    {0x6b8d37191d113e57ULL, 120, 173, 2},
    {0x6b9322449279615cULL, 612, 175, 3},
    {0x6df3276363d039edULL, 852, 178, 5},
    {0x71d85ebd63780c7cULL, 84, 183, 1},
    {0x7440512349edd030ULL, 840, 184, 5},
    {0x7bc420e871c3feccULL, 132, 189, 2},
    {0x805b21f3de3d082dULL, 240, 191, 2},
    {0x82f949746009c372ULL, 96, 193, 2},
    {0x875a7e2df3065732ULL, 204, 195, 4},
    {0x891495a8075c26d1ULL, 588, 199, 5},
    {0x8b3aa684d77d562aULL, 948, 204, 8},
    {0x92310e4cba5ba743ULL, 708, 212, 5},
    {0x932912555c1669f5ULL, 228, 217, 2},
    {0x95279cdeb7210fbaULL, 876, 219, 6},
    {0x96c722fb41c9d0afULL, 132, 225, 1},
    {0x981204bab5e460f8ULL, 132, 226, 2},
    {0x9e88a5d02c65a3a1ULL, 996, 228, 6},
    {0xa49287e4db6d4b8dULL, 168, 234, 2},
    {0xa6e58516a634514cULL, 744, 236, 8},
    {0xa70899e96f1186b6ULL, 1224, 244, 8},
    {0xacca3581ea53e78eULL, 192, 252, 2},
    {0xaf544d9e4bd5d099ULL, 96, 254, 2},
    {0xb0135bbf29f355faULL, 792, 256, 8},
    {0xb83b9bc283b1ca08ULL, 156, 264, 1},
    {0xc2da3c560804d551ULL, 216, 265, 3},
    {0xc44542f11b995cb5ULL, 876, 268, 5},
    {0xc8ac144c362cb871ULL, 804, 273, 6},
    {0xcd6da22526d53c78ULL, 1008, 279, 6},
    {0xd534397a967bf32aULL, 792, 285, 8},
    {0xd71283cda5041071ULL, 216, 293, 3},
    {0xdc6552ef6ac79d2fULL, 864, 296, 6},
    {0xde3ed701839f09b1ULL, 132, 302, 2},
    {0xe98d83edafe0096eULL, 204, 304, 3},
    {0xec4cf615564978d4ULL, 1020, 307, 5},
    {0xf31d3268877c9502ULL, 108, 312, 1},
    {0xf3ca472a261d9b34ULL, 816, 313, 5},
    {0xf48f81168af6e75fULL, 204, 318, 3},
    {0xfa891413020dac49ULL, 780, 321, 5},
    {0xfbc19b92d9ef4042ULL, 252, 326, 3},
    {0xfeed2f790be1ab5dULL, 96, 329, 2},
};
// END GENERATED METADATA

inline uint64_t Hash(std::span<const uint8_t> bytes) {
    uint64_t hash = 0xcbf29ce484222325ULL;
    for (const auto byte : bytes) hash = (hash ^ byte) * 0x100000001b3ULL;
    return hash;
}
inline std::string Name(uint64_t hash) {
    std::string name = "vs_0000000000000000.bin";
    constexpr char digits[] = "0123456789abcdef";
    for (size_t i = 0; i < 16; ++i) {
        name[18 - i] = digits[hash & 15];
        hash >>= 4;
    }
    return name;
}
inline uint32_t ReadBE(const uint8_t* bytes) {
    return uint32_t(bytes[0]) << 24 | uint32_t(bytes[1]) << 16 |
           uint32_t(bytes[2]) << 8 | bytes[3];
}
inline void WriteBE(uint8_t* bytes, uint32_t word) {
    for (unsigned i = 0; i < 4; ++i) bytes[i] = uint8_t(word >> (24 - i * 8));
}
constexpr const Element* FindElement(const Declaration& declaration, uint32_t metadata) {
    for (size_t i = declaration.first; i < size_t(declaration.first) + declaration.count; ++i) {
        const auto& element = elements[i];
        if (element.usage == ((metadata >> 12) & 15) && element.index == ((metadata >> 16) & 15))
            return &element;
    }
    return nullptr;
}
consteval bool ValidMetadata() {
    for (const auto& declaration : declarations) {
        if (!declaration.count || size_t(declaration.first) + declaration.count > std::size(elements) ||
            !declaration.extent || declaration.extent > 252) return false;
        for (size_t i = declaration.first; i < size_t(declaration.first) + declaration.count; ++i) {
            const auto& element = elements[i];
            const auto width = widths[element.format & 63];
            if (element.stream != 0 || element.offset % 4 || !width ||
                element.offset / 4 + width > declaration.extent ||
                (element.format & 0xc0) == 0x40) return false;
        }
    }
    for (const auto& source : sources) {
        if (source.size < 12 || source.size > 262144 || source.size % 12 || !source.count ||
            size_t(source.first) + source.count > std::size(fetchMetadata)) return false;
        for (size_t i = source.first; i < size_t(source.first) + source.count; ++i) {
            if (uint64_t(fetchMetadata[i] & 4095) * 12 + 12 > source.size) return false;
            for (size_t j = source.first; j < i; ++j)
                if ((fetchMetadata[i] & 4095) == (fetchMetadata[j] & 4095)) return false;
        }
    }
    return true;
}
static_assert(ValidMetadata(), "invalid fixed shader variant metadata");

using Fetch = std::array<uint32_t, 3>;
// Matching-declaration branch of SDK 0x823F2960. Unsupported byte-order
// swizzles are rejected by the metadata validator, not approximated here.
inline Fetch PatchFetch(Fetch original, const Element& element) {
    const auto type = element.format;
    uint32_t swizzle = (((type >> 10) & 0x38) | ((type >> 16) & 7)) << 3 | ((type >> 19) & 7);
    swizzle = ((swizzle << 1) | (type & 0x1c00)) << 3;
    const auto format = (((type & 0x3f) << 12) | (type & 0x300)) << 4 | (original[1] & 0xbfc0cfff);
    const uint32_t stream = (0x5f - element.stream) * 0x1560056u;
    const auto word0 = (((stream & 0x1f00) << 11) | (stream & 0x3000000)) << 1 |
                       (original[0] & 0xc00fffff);
    const auto word2 = uint32_t(element.offset & 0x1fffffc) << 6 | (original[2] & 0x80000000);
    swizzle |= 14;
    const auto a = swizzle & swizzleMasks[format & 7];
    const auto b = swizzle & swizzleMasks[(format >> 3) & 7];
    const auto c = swizzle & swizzleMasks[(format >> 6) & 7];
    const auto d = swizzle & swizzleMasks[(format >> 9) & 7];
    uint32_t word1 = (((((((a >> 3) | a) >> 3 | a) >> 3 | a) >> 3 | a) >> 1) & 7) |
                     (format & 0xfffff000);
    word1 |= ((((((b >> 3) | b) >> 3 | b) >> 3 | b) >> 1) | (b << 2)) & 0x38;
    word1 |= (((((c >> 3) | c) >> 3 | c) >> 1) | ((c << 3 | c) << 2)) & 0x1c0;
    word1 |= ((((d << 3 | d) << 3 | d) << 2) | ((d >> 3 | d) >> 1)) & 0xe00;
    return {word0, word1, word2};
}
inline unsigned Stream(const Fetch& fetch) { return ((fetch[0] >> 18) & 0x7c) | ((fetch[0] >> 25) & 3); }
inline int32_t Offset(const Fetch& fetch) {
    int32_t value = int32_t((fetch[2] >> 8) & 0x7fffff);
    return value & 0x400000 ? value - 0x800000 : value;
}
inline int32_t Width(const Fetch& fetch) { return widths[(fetch[1] >> 16) & 63]; }
// Preserve compiler-defined groups and the SDK's reserved final fetch stream.
inline void Prefetch(std::span<const uint32_t> metadata, std::vector<Fetch>& fetches) {
    size_t start = 0;
    while (start < metadata.size()) {
        while (start < metadata.size() && !(metadata[start] & 0x300000)) ++start;
        if (start == metadata.size()) break;
        size_t end = start + 1;
        while (end < metadata.size() && !(metadata[end] & 0x300000)) ++end;
        if (end == metadata.size()) break;
        const bool hasReserved = (metadata[end] & 0x300000) == 0x300000;
        const auto reserved = Stream(fetches[end]);
        const size_t last = hasReserved ? end : end + 1;
        std::stable_sort(fetches.begin() + start, fetches.begin() + last,
            [=](const Fetch& a, const Fetch& b) {
                const auto sa = Stream(a), sb = Stream(b);
                if (sa == sb) return Offset(a) == Offset(b) ? Width(a) < Width(b) : Offset(a) < Offset(b);
                if (hasReserved && sa == reserved) return false;
                if (hasReserved && sb == reserved) return true;
                return sa > sb;
            });
        size_t previous = start;
        for (size_t j = start + 1; j <= end; ++j) {
            auto& a = fetches[previous];
            auto& b = fetches[j];
            const auto streamA = ((a[0] >> 7) & 0xc0000) | (a[0] & 0x1f00000);
            const auto streamB = ((b[0] >> 7) & 0xc0000) | (b[0] & 0x1f00000);
            const auto extent = Width(b) - Offset(a) + Offset(b);
            if (streamA == streamB && Offset(a) <= Offset(b) && extent < 9) {
                const auto span = std::max(extent - 1, int32_t((a[0] >> 27) & 7));
                a[0] = (a[0] & 0xc7ffffff) | uint32_t(span & 7) << 27;
                b[1] |= 0x40000000;
            } else previous = j;
        }
        start = end + 1;
    }
}
} // namespace detail

struct FixedVariantResult {
    size_t verifiedBases = 0, missingBases = 0, invalidBases = 0, generated = 0;
    uint64_t bytesRead = 0;
    bool cancelled = false;
};

// Reads only known source names, validates exact length and the original code
// hash, then generates fixed-declaration candidates. It does not alias shader
// hashes or alter a draw's shader. Packed and 16-byte-aligned stream extents are
// bounded layout candidates, not a claim that all combinations are used.
// save is synchronous; its span expires when it returns. Save exceptions propagate.
inline FixedVariantResult GenerateFixedVariants(
    const std::filesystem::path& sourceDirectory,
    const std::function<void(uint64_t, std::span<const uint8_t>)>& save,
    const std::function<bool()>& cancelled = {}) {
    if (!save) throw std::invalid_argument("fixed shader variants require a save callback");
    FixedVariantResult result;
    std::set<uint64_t> emitted;
    for (const auto& source : detail::sources) {
        if (cancelled && cancelled()) { result.cancelled = true; break; }
        std::ifstream in(sourceDirectory / detail::Name(source.hash), std::ios::binary | std::ios::ate);
        if (!in) { ++result.missingBases; continue; }
        if (in.tellg() != std::streamoff(source.size)) { ++result.invalidBases; continue; }
        std::vector<uint8_t> code(source.size);
        in.seekg(0);
        in.read(reinterpret_cast<char*>(code.data()), std::streamsize(code.size()));
        result.bytesRead += uint64_t(in.gcount());
        if (!in || in.peek() != std::char_traits<char>::eof() || detail::Hash(code) != source.hash) {
            ++result.invalidBases;
            continue;
        }
        ++result.verifiedBases;
        const auto metadata = std::span(detail::fetchMetadata).subspan(source.first, source.count);
        for (const auto& declaration : detail::declarations) {
            std::vector<detail::Fetch> fetches;
            for (const auto elementMetadata : metadata) {
                const auto* element = detail::FindElement(declaration, elementMetadata);
                if (!element) break;
                const auto* input = code.data() + size_t(elementMetadata & 4095) * 12;
                fetches.push_back(detail::PatchFetch(
                    {detail::ReadBE(input), detail::ReadBE(input + 4), detail::ReadBE(input + 8)}, *element));
            }
            if (fetches.size() != metadata.size()) continue;
            detail::Prefetch(metadata, fetches);
            const unsigned strides[] = {declaration.extent, unsigned((declaration.extent + 3) & ~3)};
            for (unsigned strideIndex = 0; strideIndex < 2; ++strideIndex) {
                if (strideIndex && strides[0] == strides[1]) continue;
                if (cancelled && cancelled()) { result.cancelled = true; return result; }
                auto patched = code;
                for (size_t i = 0; i < metadata.size(); ++i) {
                    auto* output = patched.data() + size_t(metadata[i] & 4095) * 12;
                    detail::WriteBE(output, fetches[i][0]);
                    detail::WriteBE(output + 4, fetches[i][1]);
                    detail::WriteBE(output + 8, (fetches[i][2] & ~255u) | strides[strideIndex]);
                }
                const auto hash = detail::Hash(patched);
                if (emitted.insert(hash).second) {
                    save(hash, patched);
                    ++result.generated;
                }
            }
        }
    }
    return result;
}

struct LinkedVariantResult : FixedVariantResult {
    size_t verifiedPixelSources = 0, missingPixelSources = 0, invalidPixelSources = 0;
};

namespace detail {
consteval bool ValidLinkMetadata() {
    for (const auto& pixel : link::pixels)
        if (pixel.size < 12 || pixel.size > 262144 || pixel.size % 12) return false;
    for (const auto& plan : link::plans) {
        if (plan.source >= std::size(sources) ||
            (plan.pixel != 65535 && plan.pixel >= std::size(link::pixels)) ||
            size_t(plan.first) + plan.count > std::size(link::edits)) return false;
        for (size_t i = plan.first; i < size_t(plan.first) + plan.count; ++i) {
            const auto& edit = link::edits[i];
            if (uint64_t(edit.instruction) * 12 + 12 > sources[plan.source].size ||
                (edit.output > 15 && edit.output != 255)) return false;
        }
    }
    return true;
}
static_assert(ValidLinkMetadata(), "invalid original SDK shader link metadata");
} // namespace detail

// Additional variants from original SDK VS/PS output-link metadata. The source
// shader and representative PS are hash-checked before using a plan. Plans are
// metadata derived from source semantics and patch lists, not observed shaders.
// Existing fixed candidates are excluded; no shader identity is substituted.
inline LinkedVariantResult GenerateLinkedVariants(
    const std::filesystem::path& sourceDirectory,
    const std::function<void(uint64_t, std::span<const uint8_t>)>& save,
    const std::function<bool()>& cancelled = {}) {
    if (!save) throw std::invalid_argument("linked shader variants require a save callback");
    LinkedVariantResult result;
    std::set<uint64_t> emitted;
    const auto fixed = GenerateFixedVariants(sourceDirectory,
        [&](uint64_t hash, auto) { emitted.insert(hash); }, cancelled);
    result.bytesRead = fixed.bytesRead;
    if (fixed.cancelled) { result.cancelled = true; return result; }
    auto read = [&](uint64_t hash, uint32_t size, bool pixel, std::vector<uint8_t>& code) {
        auto name = detail::Name(hash);
        if (pixel) name[0] = 'p';
        std::ifstream in(sourceDirectory / name, std::ios::binary | std::ios::ate);
        if (!in) return 0; // missing
        if (in.tellg() != std::streamoff(size)) return -1;
        code.resize(size);
        in.seekg(0);
        in.read(reinterpret_cast<char*>(code.data()), std::streamsize(code.size()));
        result.bytesRead += uint64_t(in.gcount());
        return in && in.peek() == std::char_traits<char>::eof() && detail::Hash(code) == hash ? 1 : -1;
    };
    std::array<bool, std::size(detail::link::pixels)> pixels{};
    for (size_t i = 0; i < pixels.size(); ++i) {
        if (cancelled && cancelled()) { result.cancelled = true; return result; }
        const auto& pixel = detail::link::pixels[i];
        std::vector<uint8_t> bytes;
        const auto status = read(pixel.hash, pixel.size, true, bytes);
        pixels[i] = status == 1;
        if (status == 1) ++result.verifiedPixelSources;
        else if (status == 0) ++result.missingPixelSources;
        else ++result.invalidPixelSources;
    }
    for (size_t sourceIndex = 0; sourceIndex < std::size(detail::sources); ++sourceIndex) {
        if (cancelled && cancelled()) { result.cancelled = true; return result; }
        const auto& source = detail::sources[sourceIndex];
        std::vector<uint8_t> code;
        const auto status = read(source.hash, source.size, false, code);
        if (status != 1) {
            if (status == 0) ++result.missingBases; else ++result.invalidBases;
            continue;
        }
        ++result.verifiedBases;
        const auto metadata = std::span(detail::fetchMetadata).subspan(source.first, source.count);
        for (const auto& declaration : detail::declarations) {
            std::vector<detail::Fetch> fetches;
            for (const auto elementMetadata : metadata) {
                const auto* element = detail::FindElement(declaration, elementMetadata);
                if (!element) break;
                const auto* input = code.data() + size_t(elementMetadata & 4095) * 12;
                fetches.push_back(detail::PatchFetch(
                    {detail::ReadBE(input), detail::ReadBE(input + 4), detail::ReadBE(input + 8)}, *element));
            }
            if (fetches.size() != metadata.size()) continue;
            detail::Prefetch(metadata, fetches);
            for (const auto& plan : detail::link::plans) {
                if (plan.source != sourceIndex || (plan.pixel != 65535 && !pixels[plan.pixel])) continue;
                auto linked = code;
                for (size_t i = plan.first; i < size_t(plan.first) + plan.count; ++i) {
                    const auto& edit = detail::link::edits[i];
                    auto* instruction = linked.data() + size_t(edit.instruction) * 12;
                    if (edit.output == 255) {
                        // Original SDK output deletion instruction, not title microcode.
                        detail::WriteBE(instruction, 0xc8000000);
                        detail::WriteBE(instruction + 4, 0);
                        detail::WriteBE(instruction + 8, 0x02000000);
                    } else detail::WriteBE(instruction, (detail::ReadBE(instruction) & ~15u) | edit.output);
                }
                const unsigned strides[] = {declaration.extent, unsigned((declaration.extent + 3) & ~3)};
                for (unsigned strideIndex = 0; strideIndex < 2; ++strideIndex) {
                    if (strideIndex && strides[0] == strides[1]) continue;
                    if (cancelled && cancelled()) { result.cancelled = true; return result; }
                    auto patched = linked;
                    for (size_t i = 0; i < metadata.size(); ++i) {
                        auto* output = patched.data() + size_t(metadata[i] & 4095) * 12;
                        detail::WriteBE(output, fetches[i][0]);
                        detail::WriteBE(output + 4, fetches[i][1]);
                        detail::WriteBE(output + 8, (fetches[i][2] & ~255u) | strides[strideIndex]);
                    }
                    const auto hash = detail::Hash(patched);
                    if (emitted.insert(hash).second) { save(hash, patched); ++result.generated; }
                }
            }
        }
    }
    return result;
}
} // namespace xenos::resources::variants
