#include <cstdio>
#include <initializer_list>
#include <windows.h>
#define PPC_CONFIG_H_INCLUDED
#include <ppc_context.h>

// Only the lookup backend is substituted. The generated branch must supply
// its architectural target; observing the argument makes old unaligned calls
// safe and diagnosable, without changing the branch lowering being tested.
static uint32_t targetSeen;
static uint64_t linkSeen;
static unsigned calls;
static void Target(PPCContext& ctx, uint8_t*)
{
    ++calls;
    linkSeen = ctx.lr;
    ctx.lr = 0xBAD0; // Callee clobber must not change a saved call target.
    ctx.r7.u64 += 1;
    ctx.fpscr.enableFlushMode();
}
static PPCFunc* Lookup(uint32_t address)
{
    targetSeen = address;
    return Target;
}
static bool trapSeen;
#undef PPC_LOOKUP_FUNC
#define PPC_LOOKUP_FUNC(base, address) Lookup(uint32_t(address))
// Record old BLRL's missing lowering and stop that guest function. Avoid
// throwing C++ exceptions across generated extern-C entry points (/EHsc).
#define __builtin_debugtrap() do { trapSeen = true; return; } while (false)
#include "generated.cpp"
#undef __builtin_debugtrap

static unsigned crBits(const PPCCRRegister& cr)
{ return (cr.lt << 3) | (cr.gt << 2) | (cr.eq << 1) | cr.so; }

static void result(unsigned id, bool ok, uint64_t actual, uint64_t expected)
{
    printf("{\"id\":%u,\"ok\":%s,\"actual\":\"%016llX\",\"expected\":\"%016llX\"}\n",
        id, ok ? "true" : "false", actual, expected);
}

static void seed(uint8_t* address, uint64_t value, unsigned size)
{
    for (unsigned i = 0; i < size; ++i)
        address[i] = uint8_t(value >> ((size - i - 1) * 8));
}
static uint64_t read(uint8_t* address, unsigned size)
{
    uint64_t value = 0;
    for (unsigned i = 0; i < size; ++i) value = (value << 8) | address[i];
    return value;
}

// Tables and their exact-integer ISA expectations are generated by cases.py.
#include "cases.inc"

int main()
{
    SetErrorMode(SEM_FAILCRITICALERRORS | SEM_NOGPFAULTERRORBOX);
    // Sparse 4 GiB guest address space plus two diagnostic pages. Wrong old
    // addresses remain committed so negative controls report wrong data rather
    // than AV. This reserves virtual addresses; only 20 KiB is committed.
    constexpr size_t span = 0x100020000ull;
    auto allocation = static_cast<uint8_t*>(VirtualAlloc(nullptr, span, MEM_RESERVE, PAGE_NOACCESS));
    if (!allocation) return 2;
    auto base = allocation + 0x10000;
    for (auto offset : {int64_t(-0x1000), int64_t(0), int64_t(0x1000),
        int64_t(0xfffff000ull), int64_t(0x100001000ull)})
        if (!VirtualAlloc(base + offset, 0x1000, MEM_COMMIT, PAGE_READWRITE)) return 2;
    runCases(base);
    VirtualFree(allocation, 0, MEM_RELEASE);
    return 0;
}
