#version 450
layout(local_size_x=1) in;
layout(set=0, binding=0) uniform texture2D sourceTexture;
layout(set=0, binding=1, std430) buffer Result { vec4 values[]; } result;
layout(set=1, binding=0) uniform sampler palette[2];
layout(push_constant) uniform Push { uint samplerIndex; uint outputIndex; } pc;
void main() {
    result.values[pc.outputIndex] = textureLod(sampler2D(sourceTexture, palette[pc.samplerIndex]), vec2(-0.25, 0.5), 0.0);
}
