#!/usr/bin/env python3
"""Build the battle entry router from committed recovery metadata, not PPC inputs."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
units = {}
for path in sorted((root / 'recovery_drafts').glob('battle*.json')):
    implementation = json.loads(path.read_text())['implementation']
    units[path.stem] = implementation['entries']
entries = {}
for unit, addresses in units.items():
    for address in addresses:
        if address in entries:
            raise ValueError(f'Duplicate entry {address}: {entries[address]} and {unit}')
        entries[address] = unit
lines = ['// Generated by tools/generate_battle_semantic_routes.py.']
lines += [f'#include "lo_semantics/{unit}.h"' for unit in units]
lines += ['namespace lo::semantic::gpu::battle_semantic_runtime61 {',
          'namespace {',
          'bool Route(GuestAddress entry, GuestMemory &memory, Dependencies dependencies, Registers &state) {',
          '  switch (entry) {']
for unit, addresses in units.items():
    lines += [f'  case 0x{address.lower()}u:' for address in sorted(addresses)]
    arguments = 'entry, memory, state' if unit == 'battle_script_registration61' else 'entry, memory, dependencies, state'
    lines += [f'    return {unit}::Apply({arguments});']
lines += ['  default: return false;', '  }', '}', '}', '}']
(root / 'src/battle_semantic_routes.inc').write_text('\n'.join(lines) + '\n')
print(f'{len(units)} battle units, {len(entries)} routed guest entries')
