#version 450

layout(local_size_x = 8, local_size_y = 8) in;
layout(set = 0, binding = 0) uniform sampler2D linearColor;
layout(set = 0, binding = 1) uniform sampler2D sourceColor;
layout(set = 0, binding = 2, rgba8) uniform writeonly image2D encodedColor;

layout(push_constant) uniform Parameters {
    ivec2 size;
    ivec2 renderSize;
    ivec2 colorOrigin;
} params;

void main() {
    ivec2 p = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(p, params.size))) return;
    vec3 linear = texelFetch(linearColor, p, 0).rgb;
    ivec2 sourceP = min(ivec2((vec2(p) + 0.5) * vec2(params.renderSize) / vec2(params.size)),
        params.renderSize - ivec2(1)) + params.colorOrigin;
    float alpha = texelFetch(sourceColor, sourceP, 0).a;
    imageStore(encodedColor, p, vec4(pow(clamp(linear, vec3(0.0), vec3(1.0)), vec3(1.0 / 2.2)), alpha));
}
