#!/usr/bin/env python3
"""Emit logging stubs for every kernel import the runtime does not implement.

Reads the import symbol list dumped by tools/xexdump (<image>.bin.sym), scans the
runtime sources for GUEST_FUNCTION_HOOK / GUEST_FUNCTION_STUB / PPC_FUNC definitions
of __imp__* symbols, and writes a .cpp with a stub for each remaining import that
logs the call (once) so unimplemented kernel calls are visible at runtime.

Usage: gen_import_stubs.py <image.bin.sym> <runtime src dir> <out.cpp>
"""
import glob
import os
import re
import sys


def main(sym_path, src_dir, out_path):
    imports = []
    for line in open(sym_path):
        parts = line.split()
        if len(parts) >= 4 and parts[3].startswith("__imp__"):
            imports.append(parts[3])

    implemented = set()
    pat = re.compile(r"(?:GUEST_FUNCTION_HOOK|GUEST_FUNCTION_STUB|PPC_FUNC)\s*\(\s*(__imp__\w+)")
    for f in glob.glob(os.path.join(src_dir, "**", "*.cpp"), recursive=True):
        if os.path.abspath(f) == os.path.abspath(out_path):
            continue
        implemented |= set(pat.findall(open(f, encoding="utf-8", errors="replace").read()))

    missing = sorted(set(imports) - implemented)
    with open(out_path, "w") as fh:
        fh.write("// Generated by tools/gen_import_stubs.py. Do not edit.\n")
        fh.write("#include <stdafx.h>\n#include <kernel/function.h>\n#include <os/logger.h>\n\n")
        fh.write("#define IMPORT_LOG_STUB(name) PPC_FUNC(name) { static bool once; if (!once) { once = true; "
                 "LOG_KERNEL(\"unimplemented import {} (r3={:#x} r4={:#x} r5={:#x})\", #name, ctx.r3.u32, ctx.r4.u32, ctx.r5.u32); } ctx.r3.u64 = 0; }\n\n")
        for name in missing:
            fh.write(f"IMPORT_LOG_STUB({name});\n")
    print(f"imports={len(imports)} implemented={len(implemented & set(imports))} stubbed={len(missing)}")


if __name__ == "__main__":
    main(*sys.argv[1:4])
