"""Generate metadata-only shader offsets from user-supplied FPD resources."""
import argparse
import hashlib
import mmap
from pathlib import Path
import re
import struct


def fnv(data, value=0xcbf29ce484222325):
    for byte in data:
        value = ((value ^ byte) * 0x100000001b3) & 0xffffffffffffffff
    return value


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('root', type=Path, help='Folder containing disc1..disc4')
    parser.add_argument('output', type=Path)
    parser.add_argument("--additional-root", type=Path, action="append", default=[], help="Merge another edition into the same metadata")
    args = parser.parse_args()
    if args.output.exists():
        parser.error('Output already exists; choose a new path')
    files = []
    for root in [args.root, *args.additional_root]:
        candidates = sorted(root.glob('disc[1-4]/*.fpd'))
        if not candidates:
            parser.error(f'No disc resources found in {root}')
        files.extend(candidates)
    if not files:
        raise SystemExit('No disc resources found')
    profiles, seen = [], set()
    for path in files:
        with path.open('rb') as stream, mmap.mmap(stream.fileno(), 0, access=mmap.ACCESS_READ) as data:
            digest = hashlib.sha256(data).hexdigest()
            identity = (path.name, digest)
            if identity in seen:
                continue
            seen.add(identity)
            size = len(data)
            fingerprint = 0xcbf29ce484222325
            sample_size = min(size, 4096)
            for offset in (0, size // 4, size // 2, size - sample_size):
                fingerprint = fnv(data[offset:offset + sample_size], fingerprint)
            rows, shaders = [], set()
            for match in re.finditer(re.escape(b'\x10\x2a\x11') + b'[\x00\x01]', data):
                start = match.start()
                if start + 36 > size:
                    continue
                def be(offset):
                    return struct.unpack_from('>I', data, start + offset)[0]
                flags, virt, phys, ct, shader = be(0), be(4), be(8), be(16), be(24)
                pixel = flags == 0x102a1100
                if not (36 <= virt <= 65536 and 12 <= phys <= 262144 and start + virt + phys <= size
                        and 36 <= ct <= virt - 16 and 36 <= shader <= virt - 24):
                    continue
                if be(ct + 12) != (0xffff0300 if pixel else 0xfffe0300):
                    continue
                offset, length = be(shader), be(shader + 4)
                if length < 12 or length % 12 or offset + length > phys:
                    continue
                offset += start + virt
                code_hash = fnv(data[offset:offset + length])
                if (pixel, code_hash) in shaders:
                    continue
                shaders.add((pixel, code_hash))
                rows.append((offset, length, code_hash, pixel))
            profiles.append((path.name, size, fingerprint, digest, rows))
            print(path.parent.name, path.name, len(rows), flush=True)
    if not any(profile[4] for profile in profiles):
        raise SystemExit('No shaders found; refusing to publish an empty index')
    out = ['// Generated by tools/generate_shader_index.py. Metadata only; no shader bytecode.',
           '#pragma once', '#include "resource_index_types.h"',
           'namespace xenos::resources::builtin {']
    for i, (_, _, _, digest, rows) in enumerate(profiles):
        out.append(f'// Resource SHA256: {digest}')
        out.append(f'inline constexpr IndexEntry entries_{i}[] = {{')
        # A dummy entry keeps zero-shader profiles valid C++ (span below has zero length).
        for offset, length, code_hash, pixel in rows or [(0, 0, 0, False)]:
            out.append(f'    {{{offset}ULL, {length}, 0x{code_hash:016x}ULL, {str(pixel).lower()}}},')
        out.append('};')
    out.append('inline constexpr IndexFile files[] = {')
    for i, (name, size, fingerprint, _, rows) in enumerate(profiles):
        out.append(f'    {{"{name}", {size}ULL, 0x{fingerprint:016x}ULL, {{entries_{i}, {len(rows)}}}}},')
    out.extend(['};', '}'])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text('\n'.join(out) + '\n', encoding='utf-8')
    print(f'{len(profiles)} file profiles, {sum(len(p[4]) for p in profiles)} indexed locations')


if __name__ == '__main__':
    main()
