# Independent FG adapters. No native DLSS/FSR SR implementation is required.
option(LO_ENABLE_D3D12_DLSS_FG "Build D3D12 DLSS FG and capability-gated dynamic MFG" OFF)
option(LO_ENABLE_FSR_FG "Build independent Windows D3D12 FSR frame generation" OFF)
set(LO_FSR_FG_RUNTIME "" CACHE FILEPATH "Official FidelityFX 1.1.4 amd_fidelityfx_dx12.dll to package")
function(lo_enable_d3d12_fg target)
    if(NOT LO_ENABLE_D3D12_DLSS_FG AND NOT LO_ENABLE_FSR_FG)
        return()
    endif()
    if(NOT WIN32 OR NOT CMAKE_SIZEOF_VOID_P EQUAL 8 OR NOT LO_BUILD_GPU)
        message(FATAL_ERROR "D3D12 FG game integration requires Windows x64 and the GPU backend")
    endif()
    set(FRAMEGEN_WITH_DLSS ${LO_ENABLE_D3D12_DLSS_FG} CACHE BOOL "" FORCE)
    set(FRAMEGEN_WITH_FSR ${LO_ENABLE_FSR_FG} CACHE BOOL "" FORCE)
    set(FRAMEGEN_STREAMLINE_INCLUDE "${LO_STREAMLINE_SDK_ROOT}/include" CACHE PATH "" FORCE)
    set(FRAMEGEN_FIDELITYFX_INCLUDE "${LO_FSR_SDK_ROOT}/ffx-api/include" CACHE PATH "" FORCE)
    if(NOT TARGET framegen_d3d12)
        add_subdirectory("${CMAKE_SOURCE_DIR}/shared/frame_generation" "${CMAKE_BINARY_DIR}/framegen")
    endif()
    target_link_libraries(${target} PRIVATE framegen_d3d12)
    target_compile_definitions(${target} PRIVATE LO_ENABLE_D3D12_FG=1)
    if(LO_ENABLE_D3D12_DLSS_FG AND NOT LO_ENABLE_STREAMLINE_FG)
        lo_streamline_probe(${target})
    endif()
    if(LO_ENABLE_FSR_FG)
        if(NOT EXISTS "${LO_FSR_FG_RUNTIME}")
            message(FATAL_ERROR "LO_ENABLE_FSR_FG requires LO_FSR_FG_RUNTIME pointing to the official amd_fidelityfx_dx12.dll")
        endif()
        add_custom_command(TARGET ${target} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different
            "${LO_FSR_FG_RUNTIME}" "$<TARGET_FILE_DIR:${target}>/amd_fidelityfx_dx12.dll" VERBATIM)
    endif()
endfunction()
