# Standalone FG probe only. SDK files are supplied locally and never fetched at configure time.
set(LO_STREAMLINE_SDK_ROOT "" CACHE PATH "Extracted official NVIDIA Streamline v2.14.1 SDK")
function(lo_streamline_probe target)
    if(NOT WIN32 OR NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
        message(FATAL_ERROR "Streamline FG probe requires Windows x64")
    endif()
    foreach(_name sl.interposer sl.common sl.dlss_g sl.reflex sl.pcl nvngx_dlssg)
        if(NOT EXISTS "${LO_STREAMLINE_SDK_ROOT}/bin/x64/${_name}.dll")
            message(FATAL_ERROR "Missing official Streamline runtime: ${LO_STREAMLINE_SDK_ROOT}/bin/x64/${_name}.dll")
        endif()
        add_custom_command(TARGET ${target} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different
            "${LO_STREAMLINE_SDK_ROOT}/bin/x64/${_name}.dll" "$<TARGET_FILE_DIR:${target}>/${_name}.dll" VERBATIM)
    endforeach()
    if(NOT EXISTS "${LO_STREAMLINE_SDK_ROOT}/include/sl.h")
        message(FATAL_ERROR "Streamline SDK headers are missing")
    endif()
    target_include_directories(${target} PRIVATE "${LO_STREAMLINE_SDK_ROOT}/include")
    target_compile_definitions(${target} PRIVATE LO_STREAMLINE_SDK_VERSION="2.14.1")
endfunction()
